Make simple calculator
CodeSoom/react-week1-assignment-2 pull request #54
Opened 2021-01-19 09:58 UTC by datalater

1주차 2번 과제 제출합니다!!!!!

## 과제 해결 방법
1. 버튼 엘리먼트에 계산에 활용할 연산 값 또는 연산자를 value 속성으로 지정했습니다.
2. `handleNumber`의 관심사를 유저가 클릭한 숫자를 이어 붙이고, 이어 붙인 숫자를 렌더링을 전달하는 것으로 정했습니다.
3. `handleOperator`의 관심사를 유저가 클릭한 연산자를 저장하고, 좌항(left operand)을 등록하고, 좌항과 연산자가 존재하면 중간 계산 결과를 렌더링하도록 정했습니다.
4. `handleResult`의 관심사를 등록된 연산자와 피연산자를 계산하고 결과를 렌더링하는 것으로 정했습니다.
5. 계산하는 로직은 calculate 함수로 분리했습니다.

## 궁금한 점
1. handleOperator에 관심사가 많이 집중된 것 같은데 이게 맞는지 모르겠습니다. 참고로 관심사를 정할 때는 과제 demo 움짤을 보고 버튼이 눌리면 렌더링이 어떻게 변화되는지에 초점을 두고 정했습니다.

2021-01-19 17:44 UTC, moonkii requested changes
![Screenshot](https://user-images.githubusercontent.com/46776329/105071781-5e7ad780-5ac8-11eb-815b-336bf94fc25c.png)

쉽지 않은 로직인데 그래도 깔끔하게 잘 만드신 것 같아요 👍 

조금만 개선하면 더 좋은 결과물이 나올 것 같아요!

제가 보기엔 지금 로직에서는 1 + 1 를 입력했을 때 화면에 바로 2가 나올 것 같아요. 움짤에서는 1 + 1 까지 입력했을 때 화면에 보이는 건 1 이고 그다음 + 를 누르면 2가 보이는 구조에요.

혹시 제가 잘 못 파악 했을까요?

제가 파악한게 맞다면 설명드린 로직까지 추가되도록 해주세요 ;)

2021-01-19 17:44 UTC, moonkii commented on src/index.js
> +   */
주석으로 내 코드를 설명해야 한다면 구조를 개선해야하는 신호라고 생각하시면 돼요. 

관심사나 로직 모두 코드에서 의도가 드러나는게 좋아요.

코드의 가독성이 좋고 의도가 잘 드러난다면 주석으로 설명할 필요가 없죠.

2021-01-19 17:44 UTC, moonkii commented on src/index.js
> +    }
`switch` 문을 사용하지 않고 조건들을 표현할 수 있는 방법은 없을까요?

조건이 늘어 날 때 마다 매번 `case` 를 확인하고 반복되는 로직을 본다고 생각해보면 가독성이 떨어지고, 복잡해질 수록 코드의 의도를 파악하기 어려워 집니다.

나중에 과제를 하실 때 제한 조건으로 나오겠지만 `switch`, `if ~ else`  등은 사용하지 않는 것이 좋아요!

2021-01-19 17:44 UTC, moonkii commented on src/index.js
> +        <button type="button" value="0" onClick={handleNumber}>0</button>
이렇게 반복되는 코드는 어떻게 하면 가독성을 높이고, 의도 파악을 쉽게 만들 수 있을까요?

2021-01-19 17:44 UTC, moonkii commented on src/index.js
> +  function handleNumber(e) {
이 함수는 어떤 이벤트를 처리하는 함수인가요?

이름에서 역할이나 의도가 더 명확히 드러나면 좋을 것 같아요!

2021-01-19 17:44 UTC, moonkii commented on src/index.js
> +  function handleOperator(e) {
마찬가지로 이 함수는 어떤 이벤트를 처리하는 함수인가요?

이름에서 역할이나 의도가 더 명확히 드러나면 좋을 것 같아요!

2021-01-19 17:44 UTC, moonkii commented on src/index.js
> +};
과제 1 처럼 외부 변수에 대한 의존없이 상태를 처리할 수 있는 방법은 없을까요?

2021-01-20 05:16 UTC, datalater commented
리뷰해주셔서 감사합니다 😄 

> 제가 보기엔 지금 로직에서는 1 + 1 를 입력했을 때 화면에 바로 2가 나올 것 같아요. 움짤에서는 1 + 1 까지 입력했을 때 화면에 보이는 건 1 이고 그다음 + 를 누르면 2가 보이는 구조에요.
> 
> 혹시 제가 잘 못 파악 했을까요?
> 
> 제가 파악한게 맞다면 설명드린 로직까지 추가되도록 해주세요 ;)

아래처럼 잘 작동합니다!

![simple-calc-demo mov](https://user-images.githubusercontent.com/8105528/105130247-02e13600-5b2a-11eb-88c4-41a5e677e55e.gif)

2021-01-20 05:26 UTC, datalater commented on src/index.js
> +        <button type="button" value="0" onClick={handleNumber}>0</button>
아하 map을 사용하면 될 것 같습니다 다음 커밋에 반영할게요

2021-01-20 05:27 UTC, datalater commented on src/index.js
> +  function handleNumber(e) {
넵 handleClickNumber로 변경하겠습니다

2021-01-20 05:27 UTC, datalater commented on src/index.js
> +  function handleOperator(e) {
handleClickOperator로 변경하겠습니다!

2021-01-20 05:42 UTC, datalater commented on src/index.js
> +        <button type="button" value="0" onClick={handleNumber}>0</button>
c869155

2021-01-20 05:44 UTC, datalater commented on src/index.js
> +        <button type="button" value="0" onClick={handleNumber}>0</button>
Q. Outdated라고 뜨면 제가 resolve conversation을 누르면 되나요?

![image](https://user-images.githubusercontent.com/8105528/105132274-024a9e80-5b2e-11eb-8b14-fbbf5f888e55.png)

2021-01-20 06:18 UTC, datalater commented on src/index.js
> +    }
object literal로 변경해서 다음 커밋에 반영하겠습니다

2021-01-20 06:23 UTC, datalater commented on src/index.js
> +  function handleOperator(e) {
a9268cf

2021-01-20 06:23 UTC, datalater commented on src/index.js
> +  function handleNumber(e) {
a9268cf

2021-01-20 06:23 UTC, datalater commented on src/index.js
> +    }
7af5689

2021-01-20 07:14 UTC, datalater commented on src/index.js
> +   */
어렵네요.. 이게 저 스스로도 로직 짜고 나서 복잡하다보니 주석을 적었습니다...ㅋㅋ어떻게 접근해보면 좋을까요? 예시를 주실 수 있나요?

2021-01-20 07:15 UTC, datalater commented on src/index.js
> +};
고민이 좀 더 필요할 것 같습니다. 어떻게 접근해보면 좋을까요?

2021-01-20 16:42 UTC, moonkii commented on src/index.js
> +        <button type="button" value="0" onClick={handleNumber}>0</button>
코드를 업데이트해서 커밋하시면 제가 리뷰한 코드가 `Outdated` 가 되기 때문에 생기는 것으로 그냥 두시면 돼요!

2021-01-20 16:45 UTC, moonkii commented on src/index.js
> +};
외부 변수를 아예 없애 버리고 고민해 보세요. 

어떻게 하면 값이 전달이 될까요?

2021-01-20 16:53 UTC, moonkii commented on src/index.js
> +   */
제일 먼저 변수, 함수 명에서 내 의도가 정말 잘 드러나는지 고민해봐야 해요.

저도 프로그래밍을 할 때 가장 많이 고민하는 부분이 네이밍이에요. 

그다음에 처음엔 복잡하게 로직을 짜더라도 동작하는 프로그램을 만든 뒤  어떻게하면 이 로직을 단순하게 바꿀 수 있을까 고민해 보면 좋아요.

치열하게 고민했지만 도저히 떠오르지 않는다면 다른 사람들의 코드도 한번 참고해보세요 ;)

2021-01-21 05:52 UTC, datalater commented on src/index.js
> +};
아래 커밋으로 해결해보았습니다. 

b00f2a6

2021-01-21 06:14 UTC, datalater commented on src/index.js
> +   */
우선 연산자 버튼 핸들러에서 중간계산 결과를 드러내야 하는지 판단하는 조건문을 다음과 같이 리팩터했습니다: 

* 의도를 드러내는 이름을 가진 함수로 대체한다.

b320be0

2021-01-21 15:27 UTC, moonkii commented on src/index.js
> +        <button type="button" value="=" onClick={handleClickResult}>=</button>
코드가 반복되는 느낌이 있어요. 이부분도 간단히 줄일 수 있을까요?

2021-01-21 15:30 UTC, moonkii commented on src/index.js
> +  }
`display~BlahBlah` 라고 하면 어떤 기능을 할거라는 생각이 드시나요?

함수명과 return 해주는 결과값이 매치가 잘 되는 것 같나요?

2021-01-22 09:02 UTC, datalater commented on src/index.js
> +        <button type="button" value="=" onClick={handleClickResult}>=</button>
operator 관련 코드들을 map으로 한번에 묶겠습니다.

2021-01-22 09:06 UTC, datalater commented on src/index.js
> +  }
생각해보니 어울리지 않네요!

`shouldDisplayIntermediatResult`로 고치겠습니다.

2021-01-22 09:10 UTC, datalater commented on src/index.js
> +  }
89963bb

2021-01-22 16:07 UTC, moonkii commented on src/index.js
> +          <button type="button" value={i} onClick={handleClickNumber}>{i}</button>
`onClick` 에서 직접 함수를 실행하지 않으려고 일부러 `value` 를 넣으신건가요? 

간단히 매개변수로 받을 수 있을 것 같은데 매번 `event.target` 을 받아야해서 오히려 코드가 길어지고 가독성을 헤치는 것 같아요.

2021-01-22 16:13 UTC, moonkii commented on src/index.js
> +  initDisplay = false,
`initDisplay` 는 어떤 용도로 필요한가요?

로직을 구현하는데 반복해서 필요한 변수인가요 아니면 어떤 문제를 해결하기 위해 임시방편으로 넣은 변수인가요?

문제를 임시방편으로 사용한 변수라면 구조를 다시 한 번 생각해보는게 좋아요. 

임시방편의 해결책은 기능이 추가되고 구조가 복잡해지면 결국 근본적으로 바꿔야하는 경우가 많아지기 때문이에요.

2021-01-22 16:14 UTC, moonkii commented on src/index.js
> +  }
이 함수는 `render` 함수 안에 구현한 이유가 있나요?

2021-01-22 16:21 UTC, moonkii commented on src/index.js
> +  }
이 함수는 왜 따로 분리했을까요?

긴 함수명을 읽고 이해하는 것과 `if (operator && leftOperand !== '')` 라는 조건을 이해하는 것중 어느쪽이 더 나은 것 같나요?

무언가 함수로 분리할 때에는 코드를 그냥 읽어서 이해하는 것 보다 따로 함수명으로 코드의 의도를 이해하는게 더 좋겠다는 판단이 있을 때 하는 것이 좋아요.

2021-01-22 16:23 UTC, moonkii commented on src/index.js
> +      const displayNumber = `${calculate(leftOperand, display, operator)}`;
템플릿 리터럴을 사용한 이유가 있을까요?

2021-01-23 02:04 UTC, datalater commented on src/index.js
> +          <button type="button" value={i} onClick={handleClickNumber}>{i}</button>
생각해보니 그러네요. `event.target`을 받지 않고 매개변수로 전달하는 게 코드가 더 간단하고 좋을 것 같습니다!

2021-01-23 02:40 UTC, datalater commented on src/index.js
> +  initDisplay = false,
계산기 움짤을 보니, 넘버 버튼이 클릭되었을 때 출력하는 숫자값(이하 디스플레이)이 이전 값에다가 이어붙일 때가 있고 이전 값을 무시하고 새로운 값을 뱉는 경우가 있더라고요. 

이전 값을 무시하고 새로운 값을 뱉는 경우는 이전에 operator 버튼이 눌렸을 때이므로 계산기를 사용할 때 계속 반복되는 로직이고, 이렇게 operator 버튼이 눌렸다는 사실을 기억하는 값이 필요하다고 생각했습니다. 

따라서 디스플레이를 초기화해야 하는지 여부를 알려주는 불리언 값을 저장하기 위해 `initDisplay`를 만들었습니다.

흠.. 어떻게 하면 더 나은 방법으로 접근할 수 있을까요?

아, 그리고 변수 이름이 조금 부적절한 것 같아 `shouldInitDisplay`로 바꾸겠습니다.

2021-01-23 02:41 UTC, datalater commented on src/index.js
> +  }
생각해보니 굳이 render 함수 안에 넣을 필요가 없네요. 굳이 render 함수의 환경을 기억할 필요가 없으므로, 즉 클로저를 사용할 필요가 없는 것 같으니 render 바깥으로 두겠습니다!

2021-01-23 02:57 UTC, datalater commented on src/index.js
> +  }
음.. 저는 함수명으로 코드를 의도를 드러내려고 분리한 건데, 더 복잡해진 걸까요?🤔

`operator && leftOperand !== ''`가 중간결과를 표시해야 하는 상황이라는 이름을 붙여서 더 추상화시키면 나을 거라고 생각했습니다.

2021-01-23 02:57 UTC, datalater commented on src/index.js
> +      const displayNumber = `${calculate(leftOperand, display, operator)}`;
render 함수에서 파라미터 기본값으로 문자열 타입으로 정했기 때문에 템플릿 리터럴을 사용했습니다

![image](https://user-images.githubusercontent.com/8105528/105566942-c9294e80-5d26-11eb-9324-39c5dc594d26.png)

2021-01-23 03:03 UTC, datalater commented on src/index.js
> +          <button type="button" value={i} onClick={handleClickNumber}>{i}</button>
e6cbdc6

2021-01-23 03:04 UTC, datalater commented on src/index.js
> +  initDisplay = false,
변수 이름 변경: 2be5167

2021-01-23 03:04 UTC, datalater commented on src/index.js
> +  }
e34e2b3

2021-01-23 03:07 UTC, datalater commented
질문이 있습니다.

연산자 버튼 핸들러 함수 코드가 좀 복잡해서 어떻게 하면 복잡도를 줄일까 생각하고 있었는데요.
모든 자바스크립트 튜토리얼을 읽다가, [함수가 곧 주석 역할을 한다](https://ko.javascript.info/function-basics#ref-251)는 것을 보고 아래 커밋처럼 코드를 함수로 분리해봤습니다.

3b338fb

> 무언가 함수로 분리할 때에는 코드를 그냥 읽어서 이해하는 것 보다 따로 함수명으로 코드의 의도를 이해하는게 더 좋겠다는 판단이 있을 때 하는 것이 좋아요.

남겨주신 코멘트 기준에 위 커밋처럼 하면 해당될까요?

2021-01-23 16:56 UTC, moonkii commented on src/index.js
> +  }
꼭 정해진 답이 있는건 아니에요.

상황에 따라 혹은 개인의 판단에 따라 코드는 달라질 수 있어요.

충분히 의도를 드러내려고 분리하는 것도 좋은 시도에요.

다만 그럴경우 이름이 충분한 의도를 드러내고 있는지 고민해보면 좋겠네요 :)

2021-01-23 16:58 UTC, moonkii commented on src/index.js
> +      const displayNumber = `${calculate(leftOperand, display, operator)}`;
그러면 `calculate` 에서 문자열을 내보낼 순 없나요?

안에서 문자열로 내보내주면 밖에서는 리턴 값이 문자열인지 숫자인지 알 필요가 없게 돼요.

2021-01-23 17:21 UTC, moonkii commented
제 개인적인 견해로는 해당 부분은 분리하는 것보다 그대로 보여주는게 오히려 코드를 이해하기 쉬운 것 같아요.

계산하고나서 렌더링하는구나 정도로 간단히 이해되는 것 같아요.

오히려 `displayIntermediateResult` 라는 이름이 더 맥락 파악이 어려운 느낌이 들어요.

예를들어 `calculate` 함수의 경우는 따로 분리해줘서 복잡한 내부 로직을 이건 계산하는 거구나 라고 바로 알 수 있게 의도를 잘 드러낸 케이스라고 할 수 있어요.

2021-01-24 05:27 UTC, datalater commented
플

2021-01-24 05:28 UTC, datalater commented
엇 코멘트 쓰다가 취소를 한다는 게 모르고 클로즈 버튼을 잘못 눌렀습니다.

2021-01-24 15:22 UTC, moonkii approved these changes
과제를 잘 해결하셨어요! 👏 👏 👏 

회고도 잘 작성하셨고, 과제를 진행하시면서 고민을 많이한 흔적이 보여서 좋아요.

PR 은 merge 하겠습니다!

2021-01-31 08:41 UTC, merged