Calculate numbers
CodeSoom/react-week1-assignment-2 pull request #55
Opened 2021-01-19 12:39 UTC by HongJungKim-dev

사칙연산 계산기를 만들었습니다.
중간에 띄운 서버가 동작이 안되어서 사칙연산이 오류가 나는지 확인하지
못했습니다.
계산마다 출력하는게 아니라 '='이 와야 출력되는 형태여서 수정해야합니다.

2021-01-19 14:56 UTC, Kihyun92 requested changes

2021-01-19 14:56 UTC, Kihyun92 commented on src/index.js
> -
제거하신 공백 다시 추가해주세요. `files changed`에 코드 리뷰에 필요없는 수정은 반영하지 않는게 좋습니다.

그리고 공백을 통해서 문맥 전환도 되고 코드의 가독성이 좋아지기 때문에 적절한 위치에 사용한 공백은 좋다고 생각합니다 :)

2021-01-19 14:56 UTC, Kihyun92 commented on src/index.js
> +let operand2 = 0;
let을 사용하지 않는건 이번 과제도 동일합니다~

이번 과제의 의도를 생각해보시면서 진행하면 좋을 것 같습니다 ☺️

2021-01-19 14:56 UTC, Kihyun92 commented on src/index.js
> +  digit.push(num);
`immutable`관점에서 `push`는 최대한 사용하지 않는게 좋습니다. 변수의 값을 직접 바꾸기 때문에, 코드가 어떻게 동작할지 예측하기 어려워집니다.

2021-01-19 14:56 UTC, Kihyun92 commented on src/index.js
> +  }
switch나 if 없이 이 문제를 해결할 수 있을까요?

2021-01-20 13:02 UTC, HongJungKim-dev commented on src/index.js
> +  }
고민해보겠습니다!

2021-01-20 13:04 UTC, HongJungKim-dev commented on src/index.js
> +let operand2 = 0;
네 알겠습니다. 뭔가 감이 조금씩 오는것 같습니다. 코드가 어디서 오류 나는지 파악하기 쉽도록 최대한 immutable한 방식으로 해야할것 같습니다.

2021-01-20 13:06 UTC, HongJungKim-dev commented on src/index.js
> +  digit.push(num);
immutable한 방식으로 한다는 의미가 변수가 계속 변해서 나중에 코드를 함수마다 다 뜯어보지 않아도 쉽게 구조를 파악하고 예측가능한 코드를 만들기 위한 것이라고 이해하고 있는데 맞는것인지 궁금합니다.

2021-01-20 13:07 UTC, HongJungKim-dev commented on src/index.js
> -
임의로 수정하지말고 왜 그렇게 되어있는지 생각해야겠습니다. 그리고 공백 또한 가독성을 위한 신경쓰겠습니다.

2021-01-20 13:09 UTC, HongJungKim-dev commented on src/index.js
> +  }
아직 완벽하게 계산기가 동작하지 못하지만 객체로 대신하는것으로 시도해봤습니다. 맞는 접근인지 궁금합니다.

2021-01-20 14:17 UTC, Kihyun92 commented on src/index.js
> +  digit.push(num);
맞습니다 ㅎㅎ 결국 예측 가능한 코드를 만들기 위해서 사용하죠. push 외에도 pop, splice, shift등 불변성을 깨트리는 메서드들이 있습니다. 적절하게 잘 사용하면 좋지만 map, filter, slice등 다른 대안들을 사용하는게 좋겠죠~

2021-01-20 14:35 UTC, Kihyun92 requested changes
if나 switch를 사용하지 않기 위해 객체로 접근 하신 것 같아요! 좋습니다 👍🏼

2021-01-20 14:35 UTC, Kihyun92 commented on src/index.js
> +function render(input, num) {
매개변수가 많아질 때 어떻게 관리할 수 있을까요? 확장성 측면에서 조금 고민해보시면 좋을 것 같아요~

2021-01-20 14:35 UTC, Kihyun92 commented on src/index.js
> +            }}
함수가 꽤나 복잡하네요~ 이 경우에는 가독성 측면에서 따로 함수로 분리하는게 좋을 것 같아요~

2021-01-20 14:35 UTC, Kihyun92 commented on src/index.js
> +        {[1, 2, 3, 4, 5, 6, 7, 8, 9, 0].map((i) => (
변하지 않을 값들은 따로 선언해두는건 어떨까요?

2021-01-20 14:35 UTC, Kihyun92 commented on src/index.js
> +function calculate(operand1, operand2, operator) {
이 함수의 역할이 어떤걸까요? 이름처럼 뭔가 계산을 해주는 함수인가요?

2021-01-21 13:04 UTC, HongJungKim-dev commented on src/index.js
> +        {[1, 2, 3, 4, 5, 6, 7, 8, 9, 0].map((i) => (
const로 따로 선언하는것으로 수정하였습니다.

2021-01-21 13:07 UTC, HongJungKim-dev commented on src/index.js
> +function calculate(operand1, operand2, operator) {
이름이 모호했던것 같습니다. 말씀해주신대로 계산기도 여러종류가 있는데 사칙연산을 뜻하는것으로 분명하게 드러내야 의도를 쉽게 파악할 수 있을것 같습니다.

2021-01-21 13:16 UTC, HongJungKim-dev commented on src/index.js
> +function calculate(operand1, operand2, operator) {
커밋을 보시면 아시겠지만 if가 아닌 객체로 사칙연산 계산하는것은 성공했습니다. 하지만 화면에는 선택한 숫자를 출력할때도 있는 반면에 연산결과를 출력해야할때도 있어서 까다로웠습니다. 주석에 대략적으로 적었는데 연산과정을 출력하는 <p>부분에서 익명함수를 발생시키고자합니다.  익명함수 내부에서 if가 아닌 객체로 또 경우에 따라 현재 숫자 or 계산결과가 출력되도록 하려고합니다. 간략하게라도 틀이라도 작성해야했는데 마감기한에 생각나서 급하게 주석이라도 적어놓았습니다. 맞는 방향인지 궁금합니다.

2021-01-21 13:18 UTC, HongJungKim-dev commented on src/index.js
> +            }}
앞으로 함수가 복잡한 경우에는 따로 함수로 분리하도록 하겠습니다.

2021-01-21 13:21 UTC, HongJungKim-dev commented on src/index.js
> +function render(input, num) {
이 부분은 이번 커밋에서 Map은 사용하지 않았지만 이런 경우에 const로 저장해서 그 변수명을 넣고 작성할때 엔터로 가독성이 좋게 하는 방향이 나을것 같습니다. 맞는 접근인지 궁금합니다.

2021-01-21 14:38 UTC, Kihyun92 commented on src/index.js
> +function render(input, num) {
아 render 함수의 매개변수를 말했었던 거에요~ Map까지 선택이 되어있었네요 😭

이런 경우에는 객체로 처리할 수 있을 것 같아요 ㅎㅎ
```suggestion
function render({
  presentNumber = '0',
  previousNumber = 'X',
  presentSign = 0,
  carrier = 0,
}) {
```
이렇게되면
1. named parameter처럼 파라미터에 이름을 붙이는 것처럼 표현력이 좋아집니다.
2. optional한 값을 다루기가 쉬워집니다.
3. 의미있는 파라미터들을 객체로 묶을 수 있습니다.

- https://github.com/hannut91/refactoring-practice/tree/master/6.8-introduce-parameter-object
- https://refactoring.com/catalog/introduceParameterObject.html

2021-01-21 14:50 UTC, Kihyun92 requested changes

2021-01-21 14:50 UTC, Kihyun92 commented on src/index.js
> +          }
> 커밋을 보시면 아시겠지만 if가 아닌 객체로 사칙연산 계산하는것은 성공했습니다. 하지만 화면에는 선택한 숫자를 출력할때도 있는 반면에 연산결과를 출력해야할때도 있어서 까다로웠습니다. 주석에 대략적으로 적었는데 연산과정을 출력하는 p태그 부분에서 익명함수를 발생시키고자합니다. 익명함수 내부에서 if가 아닌 객체로 또 경우에 따라 현재 숫자 or 계산결과가 출력되도록 하려고합니다. 간략하게라도 틀이라도 작성해야했는데 마감기한에 생각나서 급하게 주석이라도 적어놓았습니다. 맞는 방향인지 궁금합니다.

말씀하신대로라면 꽤나 복잡한 예외처리가 추가될 것 같아요. 이 예외처리가 추가되는 원인이 무엇인지는 코멘트에 남겨두신 것 같아요 :) 선택한 숫자를 출력해야하고, 연산 결과를 출력해야하죠. 

그런데 이전에 등록된 연산자를 이곳에서 알 필요가 있을까요? 이 부분에서는 단순히 말씀하신 연산결과 혹은 현재 값만 노출하도록 처리할 순 없을까요? 🤔

2021-01-21 14:50 UTC, Kihyun92 commented on src/index.js
> +}
이 함수는 어떤 역할을 하는지 네이밍과 변수명을 봐도 잘 모르겠어요. 조금 더 역할을 전달하듯이 변수명 및 매개변수 네이밍을 해보면 좋을 것 같아요~

2021-01-21 14:50 UTC, Kihyun92 commented on src/index.js
> +  return pointProcess(Number.isInteger(operand1 / operand2));
형변환 처리가 왜 필요하게 된걸까요?

2021-01-21 14:50 UTC, Kihyun92 commented on src/index.js
> +            }}
굉장히 복잡하네요. 심지어 변수 선언까지 😯 이 경우에는 핸들러 함수로 분리하는게 좋을 것 같습니다!

2021-01-22 13:15 UTC, HongJungKim-dev reviewed
위에서 outdated되어서 답글을 적을 수가 없어서 여기에 남깁니다. 형변환을 하려는 목적은 아니었고 isInteger로 정수인지 판단하기 위해 Number.isInteger를 사용했습니다. 4/2는 2.0이 아니라 2로 나오고 1/3은 0.3333이 아니라 0.3이 나오게 하고 싶었습니다. 0.3이 나오게 하려고 fixPoint함수를 구현했습니다. 2로 나오게하는것은 요구사항에 없었던거 같은데 보통 계산기 처럼 하고 싶어서 추가했었습니다. 그런데 현재는 기본적인 기능 구현하는데에 괜히 코드만 많아져서 혼동이 오는것 같아서 일단 지운 상태입니다.

2021-01-22 17:22 UTC, Kihyun92 requested changes

2021-01-22 17:22 UTC, Kihyun92 commented on src/index.js
> +  isInitial = true,
관리하는 상태가 굉장히 많아졌네요. 꼭 필요한 상태와 필요하지 않은 상태가 어떤게 있을지 고민해보시면 좋겠습니다.

이 render함수는 어떤 역할을 하나요?

2021-01-22 17:22 UTC, Kihyun92 commented on src/index.js
> +  }
복잡해진 원인이 무엇일까요? 이 함수가 너무 많은 역할을 하고있다는 의미일 수 있습니다.

그리기와 계산하기를 분리해보는 것도 좋을 것 같아요~

2021-01-22 17:22 UTC, Kihyun92 commented on src/index.js
> +            }
이렇게 처리해도 될 것 같아요~
```suggestion
            onClick={
              () => handleNumberClick(num)
            }

```

2021-01-22 17:22 UTC, Kihyun92 commented on src/index.js
> +        {showing}
showing은 뭔가 보여주는 중이라는 의미같아요. 이 render함수 자체가 무언갈 그려주는 함수이고, 그 안에서 사용되는 변수는 '무언가'가 되어야할 것 같아요. 말이 조금 이상하네요😅

변수명을 조금 더 어떤 값인지를 나타낼 수 있으면 좋겠네요~

2021-01-23 14:02 UTC, HongJungKim-dev commented on src/index.js
> +        {showing}
더 값을 나타낼 수 있도록 수정하였습니다.

2021-01-23 14:26 UTC, Kihyun92 reviewed
고생하셨습니다~ 이번 과제를 진행하면서 많은 고민을 해보셨을 것 같아요. 처음 작성한 코드와 마지막 코드를 비교하면서 어떤 변화가 일어났는지 보시면 좋을 것 같아요.

그리고 과제풀이 영상을 통해서 다시 한 번 복습하면 좋을 것 같아요. 특히 아샬님은 어떻게 문제를 풀어나가는지 풀이과정을 눈여겨 보시면 좋을 것 같습니다.

2021-01-24 12:53 UTC, HongJungKim-dev commented
지난 코드들과 비교했을때 확실히 동작이 이런식으로 될거같다고 좀더 이해가 가능한 코드가 된거 같습니다. 그러면서도 지금까지 리뷰해주시면서 멘토님께서 제 코드를 보시면서 얼마나 힘드셨을까 생각이 들었습니다.  아샬님 문제풀이를 보니 정말 쉽게 푸시는것만 같았습니다. 문제를 쪼개서 하나씩 해결하시고 테스트 해보시는 과정이 그 비결이 아닐까 생각했습니다. 그것을 다음주 과제에서 숙달하고 싶습니다.

2021-01-24 13:06 UTC, HongJungKim-dev commented on src/index.js
> +  isInitial = true,
계산하는 과정의 숫자들을 그리는 함수인데 불필요한 상태들이 많았던것 같습니다.

2021-01-24 14:34 UTC, Kihyun92 commented
괜찮습니다.ㅎㅎ 이제 첫주차 끝났어요~ 사고의 전환이 되는 한주여서 힘드셨을 것 같아요
오히려 처음부터 잘하시면 저희가 할게 없다는..😂  충분히 잘하고 계십니다. 앞으로 함께 성장해보아요 ☺️

2021-01-24 14:35 UTC, merged