Fix CRLF issues
CodeSoom/react-week1-assignment-2 pull request #56
Opened 2021-01-19 12:55 UTC by dodoongtak

Due to default setting in windows vscode, switching CRLF to LF is done manually

아직 리뷰 받을 PR을 작성하지 못하였습니다. 

이어서 PR 수정 해보면 진행 해보겠습니다.

2021-01-19 14:37 UTC, Kihyun92 commented
좋습니다 👍🏼  다음 커밋을 기다릴게요 :)

2021-01-20 09:30 UTC, dodoongtak commented
현재 진행상황 : 

- 불필요한 if-else statement 제거
- 명확하지 않은 함수이름 수정 (더 나은 이름이... 떠오르지않습니다)
- " = " 을 누르고 나서 더 이상 계산기 역할 수행을 못하는 오작동 수정

수정 해야 될 사항 :

- 최대한 if를 제거하고 작동하는 코드 
( 다중의 if문으로 인해 condition들이 어떤의미로 작동하는지 한번에 파악이 되지 않음)

2021-01-20 15:08 UTC, Kihyun92 requested changes
열심히 진행해보고 계신것 같아요 👍🏼  다만 예외처리가 많아 복잡해보입니다. 예외처리가 생긴 원인을 고민해보시면 좋을 것 같아요~

2021-01-20 15:08 UTC, Kihyun92 commented on src/index.js
> +            }}
굉장히 복잡하군요. 이 부분은 가독성 측면에서 따로 함수로 분리하는게 좋을 것 같습니다.

추가로 if안의 부정문은 한번 더 생각해야해서 가독성을 떨어트리는 요인이기 때문에 긍정문으로 작성하는게 좋습니다.

2021-01-20 15:08 UTC, Kihyun92 commented on src/index.js
> +            }}
따로 핸들러 함수로 분리하는게 좋을 것 같습니다~

예외처리가 필요하게된 원인이 무엇인지 고민해보시면 좋을 것 같습니다.

2021-01-21 06:46 UTC, dodoongtak commented on src/index.js
> +  const digits = [1, 2, 3, 4, 5, 6, 7, 8, 9];
세상에...😮

후다닥 수정했습니다.

2021-01-21 07:00 UTC, dodoongtak commented on src/index.js
> +  };
반영했습니다. 

- 변수 이름은 변수의 용도에 맞게 함수와 혼동이 안되게 짖는다.
- 유틸성을 가진 경우, 재사용할 가능성이 있음으로 global context에서 관리한다.

2021-01-21 07:07 UTC, dodoongtak commented on src/index.js
> +  const signs = ['+', '-', '*', '/', '='];
operators는 부호보다는 작동기 라는 느낌이여서
부호라는 뜻을 나타내기 위해 signs를 선택했었습니다. 

operatorFunctions와 통일성을 유지하면 더 좋으니 반영해보도록할꼐요~

2021-01-21 11:44 UTC, dodoongtak commented on src/index.js
> +            }}
nested function으로 핸들러 함수 생성하여 분리하였습니다.

2021-01-21 11:47 UTC, dodoongtak commented on src/index.js
> +            }}
if 부정문 제거 진행 해보았습니다! 😄

부정문 이 외에도 변수 자체로 컨디션 작성하기 위해, 
carrier 및 presentSign 값을 변경해보았습니다.

2021-01-21 12:45 UTC, dodoongtak commented on src/index.js
> +) {
render fucntion 에서 named parameter 받은 값을 

타 함수로 인자를 보낼 떄 object 자체를 보낼 수 있는 방법은 없을까요?

//예시
```
function B({a, b}){
  console.log(a, b)
}
function A({a, b, c}){
  B({a, b}) // <- 해당 부분 named parameter로 받은 경우 원하는 인자를 넘겨 줄 떄 spread operator로 A에서 받은 인자를 보내고싶습니다. 
}
A({})
```

2021-01-21 12:54 UTC, dodoongtak commented
버튼 핸들러 함수들 안 로직이 가독성이 떨어집니다. (이해하기 어렵)

- 다수의 인자들을 보내는 상황
- 부정문은 없앴지만 아직 존재하는 if 문들 ( 더 명료한 로직이 필요? ) 

어떤 개선사항을 더 만들 수 있을까요?

2021-01-21 14:52 UTC, Kihyun92 commented on src/index.js
> +  const signs = ['+', '-', '*', '/', '='];
개인적으로는 연산자는 operator라는 매칭이 있어서 이런 피드백을드렸습니다 ㅎㅎ 본인의 의도가 묻어나는게 중요하죠~ 👍🏼

2021-01-21 14:58 UTC, Kihyun92 commented on src/index.js
> +) {
```
function B({ a, b }) {
    console.log(a, b);
}

function A(params) {
    B({...params});
}

const params = {
  a: 1,
  b: 2,
  c: 3
};

A(params);
```
위와 같이 작성할 수 있을 것 같아요~

2021-01-21 14:59 UTC, Kihyun92 commented on src/index.js
> +  };
+ `변하지 않는 경우` 입니다~

2021-01-21 15:12 UTC, Kihyun92 reviewed
> 버튼 핸들러 함수들 안 로직이 가독성이 떨어집니다. (이해하기 어렵)

예외처리가 너무 많은 것 같아요. 어떻게 하면 더 간단하게 해결할 수 있을까요? 이전이나 현재의 숫자 혹은 연산자의 상태에 따라 예외처리가 많은 것 같아요. 핸들러 함수가 아닌 계산하는 부분에서 이 처리를 해서 넘겨줄 순 없을까요? 그리기와 계산을 분리하는 것 처럼요.

> 다수의 인자들을 보내는 상황

불필요한 인자는 없는지 확인해보시고, 가능하면 객체로 넘겨주는게 좋을 것 같네요~

> 부정문은 없앴지만 아직 존재하는 if 문들 ( 더 명료한 로직이 필요? )

위쪽에 커맨트 남긴대로 예외처리가 추가되는 원인을 해결해보셔야 할 것 같습니다!

> render 함수에 선언한 digit 및 oeprators 같은 경우 없애는게 좋을까요? 아니면 operatorFunctions처럼 global context에 하는게 좋을까요?

마찬가지로 변하지 않을 변수들 같아요. render 함수 바깥에서 선언하는게 좋을 것같습니다~

2021-01-21 21:26 UTC, dodoongtak commented on src/index.js
> +) {
기현님이 알려주신데로 변경을 진행해보았습니다. 

그런데 params라는 선언된 변수가 mutate 될 가능성을 고려 해 본 결과 

차라리 function A 에서 

```
function A(params) { 
 const { a, b} = params; // Destructuring을 통해 관리

 A(...params, b :  B(params)) // 이런 식으로 변동 되는 부분만 value를 부여하여 진행
}
```

이런 방식으로 object 를 관리해보았습니다.

2021-01-22 11:43 UTC, dodoongtak commented
- 함수가 각각 하나의 목적을 가지고 작동하기위해 분리를 진행해봤습니다. 
기현님 말씀대로 그리는 함수는 그리는 목적으로만 계산은 계산을 목적만을 가지도록
코드를 분리해 따로 처리를 진행했습니다. 

- 이 과정에서 하나의 함수에 여러 복잡한 task를 부여하면
추 후에 파악하기도 어렵고 수정 및 관리하는 시간이 비약적으로 높아질거라 생각되네요. 

테스트 케이스 이 외에도 보통 계산기라면 고려해야 될 케이스들도 작동되게 수정 해볼려합니다. 
1. = 클릭 이 후 저장된 번호와 계속 이어 질 수있게 계산 ex 1 + 2 = + 1
2. operator를 연속으로 클릭 시에 마지막으로 클릭된 operator로 정상 작동


이번 과제에서는 개념들을 두루두루 살펴보기 보다는 코드작성을 우선하였습니다.
너무 깊게는 아니지만 메카니즘을 살펴봐야 다음에도 쉽게 적용하며 이어 나갈 수 있을거라 생각되네요. 

list to follow up : 
- arrow function
- nested function ( scope, closure... etc)
- pure function
- side effects
- managing object

2021-01-22 18:22 UTC, Kihyun92 reviewed
리뷰를 잘 반영해주셨네요! 그리고 계산기에서 보완해야할 케이스들에 대해서도 고민해보신게 좋습니다 👍🏼 

> Q1. 전체적으로 제 현재 branch 커밋이 어떻게 보이는지 말씀 해 주실 수 있을까요?

커밋 메시지는 잘 작성해주고 계셔서 별다른 커맨트를 아직 하지 않았습니다 ㅎㅎ 아무래도 기능 작업 외에 리팩터링을 하며 하나씩 수정해가는 작업이 커밋을 쪼개기가 매우 힘들죠. 추후에 테스트 코드를 작성해볼때는 이제 커밋 메시지를 `red-green-refactoring` 단위로 가져가게 되어 조금 더 체계적인 느낌을 받을 수 있을 것 같네요.

이미 보셨겠지만 참고해주세요. 좋은 자료 있으면 공유드리겠습니다~
- https://github.com/ikaruce/git-style-guide

2021-01-23 12:59 UTC, dodoongtak commented
operator를 연속으로 클릭 시에 마지막으로 클릭된 operator로 정상 작동 ex. 1 + + + - 2 =

해당 케이스 중에 

/ 혹은 * 를 다 수 클릭 시 계산기가 망가지는 원인은 찾았습니다. 
원인은 부호가 있는 상태를 클릭 할 떄마다 compute을 실행하기 떄문입니다. 
덧셈뺼셈은 null인 상태값과 계산하기에 별반 차이없지만 
곱셈 나눗셈은 presentNumber가 null로 된 상태이기에 computer를 한번 더 실행하는순간 0 그리고 null 로 결과로 이어지네요 
```
function handleCalculation({ presentNumber, previousNumber, presentSign }, operator) {
  if (presentSign) {
    return ({
      presentNumber: null,
      previousNumber: operatorFunctions[presentSign](previousNumber, presentNumber), <- 요부분
      presentSign: 0,
    });
  }
  return ({ presentNumber: null, previousNumber: presentNumber, presentSign: operator });
}
```

계속 수정하면서 도전했는데 아직가지 해결방법을 찾지를 못하겠네요. ㅠㅠ 
(야살님 해설 코드에서도 이 케이스는 포함시키지 않으셨습니다.)

2021-01-23 14:33 UTC, Kihyun92 approved these changes
고생하셨습니다 ㅎㅎ 이번 과제를 진행하면서 정말 많은 고민을 해보신 것 같아요~ 처음 작성한 코드와 마지막 코드를 비교하면서 어떤 변화가 일어났는지 보시면 좋을 것 같습니다.

그리고 과제풀이 영상을 통해서 반복해서 복습하면 좋을 것 같아요. 특히 아샬님은 어떻게 문제를 풀어나가는지 풀이과정을 눈여겨 보시면 좋을 것 같습니다.

2021-01-23 14:39 UTC, Kihyun92 commented
> operator를 연속으로 클릭 시에 마지막으로 클릭된 operator로 정상 작동 ex. 1 + + + - 2 =
> 
> 해당 케이스 중에
> 
> / 혹은 * 를 다 수 클릭 시 계산기가 망가지는 원인은 찾았습니다.
> 원인은 부호가 있는 상태를 클릭 할 떄마다 compute을 실행하기 떄문입니다.
> 덧셈뺼셈은 null인 상태값과 계산하기에 별반 차이없지만
> 곱셈 나눗셈은 presentNumber가 null로 된 상태이기에 computer를 한번 더 실행하는순간 0 그리고 null 로 결과로 이어지네요
> 
> ```
> function handleCalculation({ presentNumber, previousNumber, presentSign }, operator) {
>   if (presentSign) {
>     return ({
>       presentNumber: null,
>       previousNumber: operatorFunctions[presentSign](previousNumber, presentNumber), <- 요부분
>       presentSign: 0,
>     });
>   }
>   return ({ presentNumber: null, previousNumber: presentNumber, presentSign: operator });
> }
> ```
> 
> 계속 수정하면서 도전했는데 아직가지 해결방법을 찾지를 못하겠네요. ㅠㅠ
> (야살님 해설 코드에서도 이 케이스는 포함시키지 않으셨습니다.)

현재 과제는 4+3+ 와 같이 연산자를 눌렀을 경우 계산 결과를 나타내주고 있죠. 추가적인 기능구현을 위해 잠깐 생각해봤을땐 연산자가 눌렸을때 이전 계산을 진행하고, 현재 연산자는 따로 저장하는 방법 밖에 생각이 나지 않네요. 🤔

2021-01-23 14:55 UTC, shinhyogeun commented
사칙연산을 정의 하는 부분을 
`const caclulator = {
  '+': (x, y) => x + y,
  '-': (x, y) => x - y,
  '*': (x, y) => x * (y || 1),
  '/': (x, y) => x / (y || 1),
}` 처럼 수정하면 어떤가요?

2021-01-24 12:27 UTC, dodoongtak commented
효근님과 의기투합해서 페어프로그래밍을 진행해봤습니다. 

다른 케이스들 및 불필요했던 컨디션과 추가적인 리셋기능을 포함해봤습니다. 

효근님 그저 빛... 🙌🙌

야살님 튜토리얼 보면서 어떤 풀이방식으로 진행하는지 다시 되짚어보고,
계산기를 다시 처음 베이스부터 작섬함으로, 어떤 부분을 놓치고 있는지 짚어봤습니다. 아직 가야될 길이.. 멀...

다음 과제에도 이어서 적용해보도록 하겠습니다. 

많은 리뷰 달아주셔서 감사합니다.

2021-01-25 14:09 UTC, merged