make Calculator
CodeSoom/react-week1-assignment-2 pull request #58
Opened 2021-01-19 13:00 UTC by shinhyogeun

일단은 첫번째 과제까지만 적용해보았습니다. 한번이라도..
다음으로 함수를 만들어야하는데 상당히 막막합니다..ㅠㅠ 
함수들의 관계를 이용해야할 것 같은데 힌트라도 얻으려고 일단 PR을 보낼게요~! 🥺

2021-01-19 14:59 UTC, Kihyun92 reviewed
막막하거나 맞는 방향으로 잘 하고 있는지 모르실땐, 가능한 작은 기능 단위로 쪼개고 하나하나 해결 해보는건 어떨까요?

예를 들면 숫자 버튼 눌렀을때 숫자 노출되게하고, 그 다음 십의 자리, 백의 자리수까지 표현이 가능하게 하고, 다음으로 더하기 기능도 추가하는 방식 처럼요. 이런식으로 점진적으로 작업을 진행해보셔도 좋을 것 같습니다~

그리고 중간 중간 의미있는 성과가 나타났을때 커밋을 남김으로써 혹시라도 길을 잃었을 경우, 다시 돌아갈 수 있게 하는 것도 좋을 것 같습니다 :)

2021-01-19 14:59 UTC, Kihyun92 commented on src/index.js
> +  value.push(count);
`immutable` 관점에서 `push`는 최대한 사용하지 않는게 좋아요. 
변수의 값을 직접 바꾸기 때문에, 코드가 어떻게 동작할지 예측하기 어려워지기 때문이죠 :)

2021-01-19 18:08 UTC, shinhyogeun commented
감사합니다!! 기능별로 침착하게 진행해보도록 하겠습니다😃

2021-01-20 12:21 UTC, shinhyogeun commented
어제 주신 리뷰를 참고해서 어제부터 오늘까지 정말 많이 생각을 하면서 구현에 겨우 성공했습니다.😂😂
하지만 리팩토링이 필요한 부분이 있는 것같습니다. 제가 나름 생각했을 때는 다음과 같은 것을 생각해볼 수 있었습니다. 
1. 외부에 객체를 사용하지 않는다. 
2. if를 사용하지 않는다. 
혹시 더 유념해서 refactoring을 해야하는 부분이 있을까요?

2021-01-20 12:36 UTC, shinhyogeun commented on src/index.js
> +  value.push(count);
그 부분은 재귀로 피했지만.. 객체 내부의 배열에 push를 사용했습니다 ㅠㅠ

2021-01-20 15:25 UTC, Kihyun92 requested changes
객체를 사용해서 문제를 해결해보신 것 같아요. 좋습니다ㅎㅎ 다만 이번 과제의 의도를 생각하며 한번 더 고민해보시면 좋을 것 같아요.

복잡해지고 예외처리가 생기게된 원인들이 무엇일까요?

2021-01-20 15:25 UTC, Kihyun92 commented on src/index.js
> +            }}
복잡해 보입니다. 가독성 및 관리 측면에서 이 부분은 핸들러 함수로 분리하는게 좋을 것 같아요~

2021-01-20 15:25 UTC, Kihyun92 commented on src/index.js
> +      <p>{['+', '-', '*', '/', '='].map((operator) => <button type="button" onClick={() => calculate(operator, count)}>{operator}</button>)}</p>
이 부분도 핸들러 함수로 분리해주세요.

2021-01-20 15:25 UTC, Kihyun92 commented on src/index.js
> +        {[1, 2, 3, 4, 5, 6, 7, 8, 9, 0].map((number) => (
숫자 배열은 변하지 않기 때문에 함수 바깥에서 상수로 관리해도 좋을 것 같아요~

2021-01-20 15:25 UTC, Kihyun92 commented on src/index.js
> +    calculator.process.push(operator);
push, splice와 같은 메소드의 문제점은 원본 컬렉션의 변경이 일어난다는 점입니다.
바로 Side effect죠. 앞으로 push와 splice는 사용하지 않는 걸 권합니다.

push와 같은 효과는 spread operator를 사용하면 됩니다. 사본을 만들기 때문에 Side effect가 없죠.
`[...numbers, number]`

2021-01-20 15:25 UTC, Kihyun92 commented on src/index.js
> +    if (calculator.process.length === 4) {
`calculator.process.length === 4` 가 의미하는게 뭔지 모르겠어요. 조금 더 의도를 나타내려면 어떻게 할 수 있을까요?

2021-01-20 15:25 UTC, Kihyun92 commented on src/index.js
> +      render(calculator.process[0]);
[1]이 무엇이고 [0], [3]가 무엇인지 가늠하기 어려운 것 같아요. 디스트럭처링을 사용하면 의도를 더 드러낼 수 있을거에요.

```javascript
function calculateNumbers() {
  const [x, operator, y] = calculateContent;

  switch(operator) {
    case '+':
      return x + y;
  }
}
```

- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment

2021-01-20 15:25 UTC, Kihyun92 commented on src/index.js
> +      };
객체를 사용해서 처리한 부분은 굉장히 좋네요!

다만 변수명을 보고 어떤 역할을 하는지 알 수 없는 것 같아요. 

또한 함수 바깥으로 빼면 어떨까요? 재사용 가능해 질 것이고, 테스트가 쉬워 질 것 같아요.

2021-01-20 15:25 UTC, Kihyun92 commented on src/index.js
> +  }
이 함수가 필요하게된 원인이 무엇일까요?

2021-01-21 07:14 UTC, shinhyogeun commented on src/index.js
> +            }}
1 + 1 에서 또하면 +를 누르면 2를 보여줘야하지만 1 입력후 +를 입력할때는 계산할게 없으니 결과를 보여줄 필요가 없습니다. 
이 부분에서 if를 사용하게 되고 복잡하게 되는 부분인 것 같습니다. 계산할게 있을 때와 없을 때를 통일적을 바꿀 필요가 있어보입니다!!

2021-01-21 07:16 UTC, shinhyogeun commented on src/index.js
> +    if (calculator.process.length === 4) {
계산의 과정을 배열을 이용해서 하니 가독성이 너무떨어지네요.. 객체를 이용해서 좀 더 가독성을 높이겠습니다!

2021-01-21 11:13 UTC, shinhyogeun commented on src/index.js
> +        {[1, 2, 3, 4, 5, 6, 7, 8, 9, 0].map((number) => (
네 구현하겠습니다!!👍

2021-01-21 11:13 UTC, shinhyogeun commented on src/index.js
> +    calculator.process.push(operator);
와.. 정말 유용한 기법인 것 같습니다.. 코딩의 기술이라는 책을 읽는데 읽기만 하고 생각을 못했었네요..ㅠㅠ

2021-01-21 11:14 UTC, shinhyogeun commented on src/index.js
> +      render(calculator.process[0]);
배열을 사용하지 않는 방향으로 구현해보았습니다!!

2021-01-21 11:16 UTC, shinhyogeun commented on src/index.js
> +      <p>{['+', '-', '*', '/', '='].map((operator) => <button type="button" onClick={() => calculate(operator, count)}>{operator}</button>)}</p>
혹시 핸들러 함수가 `onClick = {() => calculate(operator,count)}` 이 부분 아닌가요? 
여기를 어떻게 수정해야하는지 잘 모르겠어요..😭😭
(제가 핸들러 함수를 잘못 이해하고 있는 건가요??)

2021-01-21 11:32 UTC, shinhyogeun commented on src/index.js
> +  }
위의 말씀을 깊게 생각해봤습니다. 일단은 제 코드가 복잡해진 이유를 제가 나름 생각해봤을 때 저의 함수가 경우에 따라 다른 일을 한다고 생각했습니다. 그 경우는 처음에 숫자를 입력하고 그 다음에 연산자를 입력할 때는 연산이 되면 안된다고 생각했습니다. 하지만 꼭 그럴 필요는 없었습니다. 처음에 연산자 버튼을 누르면 + 0 이 실행됩니다. 이것은 그 다음부터 경우에 상관없이 같은 일을 반복하게 하기 위해서 그렇습니다. 또한 연산자를 입력 후 숫자를 누르면 화면이 초기화되어야하는 것도 3항 연산자를 이용하여 연산의 진행 후를 인식할 수 있게 했습니다. 하지만 아직도 뭔가 리팩토링이 필요해 보입니다.😂😂😂

2021-01-21 15:15 UTC, Kihyun92 commented on src/index.js
> +            }}
스스로 해결법을 찾아보고 계신것 같네요 좋습니다 👍🏼

2021-01-21 15:22 UTC, Kihyun92 commented on src/index.js
> +    calculator.process.push(operator);
정말 유용한 책이죠~ 저도 볼때마다 새롭네요😂 
이것저것 적용해보세요👍

2021-01-21 15:33 UTC, Kihyun92 requested changes
리뷰를 잘 반영해주시는 것 같아요 👍🏼 

맞아요 복잡해진 이유는 여러 역할을 동시에 처리하려고 해서 입니다. 그에 맞춰 예외처리가 추가되다보면 끝도없죠.. 😭

일단 그리기와 계산하기를 분리해보는 것을 추천드립니다~

2021-01-21 15:33 UTC, Kihyun92 commented on src/index.js
> +}) {
```suggestion
function render({
  left: 0,
  operator: '+',
  rigth: 0,
  nextOperator: '+',
}) {
```

이렇게 처리되면 객체로 받은걸 다시 info에 할당해주게 됩니다. (도루묵 느낌..?😅) 이렇게 처리하는게 좋겠군요!

- https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#%ED%95%A8%EC%88%98_%EB%A7%A4%EA%B0%9C%EB%B3%80%EC%88%98%EB%A1%9C_%EC%A0%84%EB%8B%AC%EB%90%9C_%EA%B0%9D%EC%B2%B4%EC%97%90%EC%84%9C_%ED%95%84%EB%93%9C_%ED%95%B4%EC%B2%B4%ED%95%98%EA%B8%B0

2021-01-21 15:33 UTC, Kihyun92 commented on src/index.js
> +  const operators = ['+', '-', '*', '/', '='];
변하지 않을 값이고, 재활용 및 테스트가 용이하도록 render 함수 바깥으로 분리하는게 좋을 것 같습니다~

2021-01-21 15:33 UTC, Kihyun92 commented on src/index.js
> +    };
case라는 변수명이 해당 객체를 적절하게 드러내지 않는것 같아요. operators와 같은 네이밍은 어떨까요?

이 객체도 마찬가지로 변하지 않을 것 같고, 재사용 및 테스트가 용이하도록 함수 바깥으로 분리해도 좋을 것 같습니다~

2021-01-21 15:33 UTC, Kihyun92 commented on src/index.js
> +  nextOperator: '+',
left, right는 본인만 이해할 수 있는 네이밍 같아요! 각각 어떤 역할을 하는지 동료가 봤을때 쉽게 이해할 수 있도록 작성해주세요~

2021-01-22 08:24 UTC, shinhyogeun commented on src/index.js
> +}) {
말씀해주신대로 반영했습니다!!👍

2021-01-22 08:27 UTC, shinhyogeun commented on src/index.js
> +  const operators = ['+', '-', '*', '/', '='];
바깥으로 분리했습니다 !! 하지만 궁금한 점이 하나 있습니다. numbers와 operators는 render를 하기위해 반드시 필요한 요소인데
함수의 바깥으로 보내면 render를 test할 때 이것도 같이 test할 파일로 가져가야하지 않나요? 그렇다고 함수의 인자로 받으면 인자가 너무 많아지는 것같아서요..ㅠㅠ

2021-01-22 08:28 UTC, shinhyogeun commented on src/index.js
> +    };
operateCase로 네이밍 변경했습니다!

2021-01-22 08:28 UTC, shinhyogeun commented on src/index.js
> +  nextOperator: '+',
넵.. leftNumber와 rightNumber로 바꾸었습니다.

2021-01-22 12:49 UTC, shinhyogeun commented
render함수를 실행하면서 operate button onclick의 이벤트핸들러함수 그 속에 calculate함수가 있어야 합니다. 그래서 render속에서 calculate를 쓰는 것을 피할 수 없는 것같습니다..ㅠㅠㅠ 하지만 그와 반대로 calculate함수에서는 굳이 render를 실행할 필요가 없습니다. 그런데
리뷰해주신 저의 코드에서는 calculate함수 마지막에 render가 있었습니다. 이 부분은 없엘 수 있었습니다. 그래서 보다 독립적이게 calculate함수는 객체를 받아 계산을 해서 객체를 반환하는 함수로 만들었습니다. 하지만 render함수안에서 calculate함수를 쓰는 것을 피할 수 없다고 생각해서 render속에 calculate함수를 넣었습니다. 하하.. 이게 맞는 걸까요..ㅠㅠ(아샬님이 주신 힌트도 이것과 관련되어있어보여서..히히..🥲)
어떻게하면 더 테스트하기 쉽게 만들지 모르겠습니다.😭🥺😭🥺

2021-01-22 17:33 UTC, Kihyun92 commented on src/index.js
> +  const operators = ['+', '-', '*', '/', '='];
테스트는 주로 함수 단위로 진행됩니다. 때문에 이렇게 상수로 선언해둔 값은 실행되면서 함수 스코프 내에서 가져와서 알아서 처리하게 되어 우리가 신경 쓸 필요가 없어지겠죠.

2021-01-22 17:36 UTC, Kihyun92 commented on src/index.js
> +    };
operators 혹은 operatorFunctions라고만 해도 될 것 같아요~ case라는 말은 굳이 필요 없을 것 같기도 합니다 ㅎㅎ

테스트 관련해서 좋은 고민을 해보시는 것 같아요 넘 좋습니다! 위쪽에 커맨트를 남겨봤는데, 혹시 이해가 안되거나 더 의논이 필요하면 편하게 말씀주세요~

2021-01-22 17:37 UTC, Kihyun92 commented on src/index.js
> +  nextOperator: '+',
숫자라는 의미를 담아주셨네요 ㅎㅎ 좋습니다~

다만 계산기 측면에서 봤을때 left, right라는 정보가 필요할까요? 

누적되는 값과 새로 입력된 값은 어떤가요?

2021-01-22 17:56 UTC, Kihyun92 requested changes
> 양질의 코드리뷰를 해주셔서 감사합니다.. 하루동안 한 일을 점검받을 수 있어서 좋아요👍👍👍 질문이 하나 있습니다!!
render함수를 실행하면서 operate button onclick의 이벤트핸들러함수 그 속에 calculate함수가 있어야 합니다. 그래서 render속에서 calculate를 쓰는 것을 피할 수 없는 것같습니다..ㅠㅠㅠ 하지만 그와 반대로 calculate함수에서는 굳이 render를 실행할 필요가 없습니다. 그런데 리뷰해주신 저의 코드에서는 calculate함수 마지막에 render가 있었습니다. 이 부분은 없엘 수 있었습니다. 그래서 보다 독립적이게 calculate함수는 객체를 받아 계산을 해서 객체를 반환하는 함수로 만들었습니다. 하지만 render함수안에서 calculate함수를 쓰는 것을 피할 수 없다고 생각해서 render속에 calculate함수를 넣었습니다. 하하.. 이게 맞는 걸까요..ㅠㅠ(아샬님이 주신 힌트도 이것과 관련되어있어보여서..히히..🥲)
어떻게하면 더 테스트하기 쉽게 만들지 모르겠습니다.😭🥺😭🥺

작업하면서 느끼신점을 잘 적어주셔서 아무래도 리뷰하기 좋았던 것 같습니다 👍🏼  

힌트를 잘 적용하신 것 같아요~ 지금 복잡해 보이는 이유는 매개변수로 넘기는 상태들이 너무 많은 것 같아요. 해당 함수에서 필요로하는 상태들이 어떤게 있을지, 그리고 불필요하게 사용되는 매개변수는 없을지 고민해보시면 좋겠습니다!

2021-01-22 17:56 UTC, Kihyun92 commented on src/index.js
> +    };
아래 처럼 lookup을 함수로 만들고, 해당 lookup을 바로 호출하는 형식은 어떤가요? calculatedLeftNumber 와 같은 변수명은 굳이 필요 없는것 같아요.

``` javascript
// calculate 함수 lookup
const operators = {
    '+': (x, y) => x + y,
    '-': (x, y) => x - y,
    '*': (x, y) => x * y,
    '/': (x, y) => x / y,
  };

//  호출
const result = calculate[operator](x, y);
```

2021-01-22 17:56 UTC, Kihyun92 commented on src/index.js
> +          </button>
```suggestion
        {operators.map((operator) => (
          <button type="button" value={operator} onClick={handleClickOperator}>
            {operator}
          </button>
```

`oper`와 같이 줄여서 사용하는건 좋지 않습니다. 물론 충분히 문맥상 유추 가능하지만, 본인만이 생각하는 의미를 동료들에게 이해되지 않을 수 있습니다. 최대한 명확하게 코드를 작성해주세요 :) 

그리고 핸들러 함수의 네이밍도 `handleClick~~`과 같이 작성하는게 좋을 것 같습니다.
- https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Event_handlers
- https://reactjs.org/docs/handling-events.html
- https://blog.sonim1.com/220

2021-01-22 17:56 UTC, Kihyun92 commented on src/index.js
> +render({});
```suggestion
render();
```
이렇게만 처리해도 될 것 같아요~

2021-01-23 07:53 UTC, shinhyogeun commented on src/index.js
> +  const operators = ['+', '-', '*', '/', '='];
그러면 상수를 render 함수 바깥에 두는 게 좋은 것인가요?😮(위에서 상수를 render 밖으로 빼라고 하셔서..)함수단위로 테스트하므로 함수 바깥으로 상수를 빼면 오히려 테스트가 어려워지는것아닌가요??

2021-01-23 07:53 UTC, shinhyogeun commented on src/index.js
> +    };
네 위에 코멘트 남겼습니다~!!

2021-01-23 07:55 UTC, shinhyogeun commented on src/index.js
> +  nextOperator: '+',
와.. 그 생각을 못했었네요!! 변수명도 한참 생각하고 만들겠습니다!!👌👍🏻

2021-01-23 10:56 UTC, shinhyogeun commented on src/index.js
> +          </button>
넵 반영했습니다!!

2021-01-23 10:57 UTC, shinhyogeun commented on src/index.js
> +    };
lookup이라는 말을 처음들어보네요!! 오.. 보여주신 예시를 반영해서 새롭게 만들었습니다!☺️

2021-01-23 10:59 UTC, shinhyogeun commented
해설 강의가 열렸지만 오늘까지는 저의 코드로 작성해보았습니다! 1주일동안 깊게 고민해봤던 것이 좋았던 것 같아요! 또한 매개변수가 많은 것같아서 생각해보니 nextOperator는 필요 없어서 제거 해서 코드를 간결하게 만들었습니다!👍👍

2021-01-23 14:58 UTC, Kihyun92 commented
고생하셨습니다~ 이번 과제를 진행하시면서 정말 많은 고민을 해보신 것 같아요! 😊  처음 작성한 코드와 마지막 코드를 비교하면서 어떤 변화가 일어났는지 보시면 좋을 것 같아요.

그리고 과제풀이 영상을 통해서 다시 한 번 복습하면 좋을 것 같아요. 특히 아샬님은 어떻게 문제를 풀어나가는지 풀이과정을 눈여겨 보시면 좋을 것 같습니다.

> 마지막 질문으로 혹시 const로 함수 바깥으로 지금 3개의 상수를 뺐는데 지금처럼 함수 바깥에 두는 것이 좋은가요?(함수단위로 테스트가 돌아가면 상수도 함수 안에 있어야 깔끔한거 아닌가요?)🥲🥲

제 [답변](https://github.com/CodeSoom/react-week1-assignment-2/pull/58#discussion_r562791539)이 조금 부족했던 것 같아요 😅 

render 함수를 테스트할 경우, 테스트 코드에서 render 함수를 실행하게 될 거에요. 이때 함수 스코프 체인에 따라 함수 바깥에 상수로 선언해둔 `numbers, operators`를 찾아서 사용하게 됩니다.
테스트시 `numbers, operators`와 같이 객체나 배열이 아닌 원시값(숫자, 문자열, 불린 등)을 할당하여 선언해둔 상수값들은 변하지 않기 때문이죠. 신경 쓸 필요가 없게 됩니다.

scope-chaining과 lexical-chaining이 연관되어 있습니다. 첨부해드린 문서 한번 확인해보시고 더 의논이 필요하다면 말씀주세요~
- https://medium.com/@yeon22/javascript-lexical-scope-static-scope-and-dynamic-scope-c4a9e941fab3
- https://www.zerocho.com/category/JavaScript/post/5740531574288ebc5f2ba97e

2021-01-23 14:59 UTC, Kihyun92 approved these changes

2021-01-23 15:00 UTC, Kihyun92 commented
추가로 풀 리퀘스트를 CodeSoom:<user-github-id>로 보내주세요. 잘못 설정했을 경우 간단히 상단에 Edit을 눌러 수정할 수 있습니다~
일단 제가 수정해둘게요 :)

2021-01-24 10:13 UTC, shinhyogeun commented
최종으로 수정해서 올렸습니다! 다음주에도 잘 부탁드립니다~!👍

2021-01-25 14:10 UTC, merged