Solved second problem except lint error
CodeSoom/react-week1-assignment-2 pull request #61
Opened 2021-01-19 15:11 UTC by 2Zero1

린트는 통과하지 못했지만 너무 피곤해서 잠을 자야겠다.
오늘 회사일로 기분이 아주 않좋다. 아주 화가난다. 코드숨은 내 삶 낙이다. 뭔가 안풀리면 약오르지만 뭔가 재미있다. 내일 아침 일찍 일어나서 리팩터링이랑 다르게 풀 수 있는 방법을 찾아봐야겠다.

2021-01-20 15:32 UTC, Kihyun92 requested changes
리뷰하기가 쉽지 않네요. 😭 
린트 에러는 가능하면 해결해서 푸시해주시면 좋을 것 같습니다~

2021-01-20 15:32 UTC, Kihyun92 commented on src/index.js
> +    switch (operator) {
`if`문과 `switch`문을 사용하지 않고 해결할 수 있을까요?

2021-01-20 15:32 UTC, Kihyun92 commented on src/index.js
> +function click(cur, char, arr) {
조금 더 의미가 전달되는 변수명을 사용하는게 좋을 것 같아요. `handleClick~~`와 같이 클릭에 대한 어떤 수행인지가 나타나면 좋을 것 같습니다.

참고
- https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Event_handlers
- https://reactjs.org/docs/handling-events.html
- https://blog.sonim1.com/220

2021-01-20 15:32 UTC, Kihyun92 commented on src/index.js
> +function render(cur = 0, display = 0, arr = []) {
render에 많은 파라미터들이 넘어오고 있어 복잡해지는것 같습니다. 이 상태값들을 같은 의미를 가지는 객체로 묶는건 어떨까요?

2021-01-20 15:32 UTC, Kihyun92 commented on src/index.js
> +      <button type="button" onClick={() => cal(cur, [...arr, '='])}>=</button>
반복되는 로직이 많은 것 같습니다~ 배열을 이용해서 처리하면 어떨까요?

2021-01-21 15:48 UTC, Kihyun92 commented on src/index.js
> +}
이 함수는 단순히 매개변수를 받아서 객체로 리턴하고 있네요. 이걸 사용하는 부분에서 객체를 동일하게 리턴하면 이 함수는 제거할 수 있을 것 같네요

2021-01-21 15:48 UTC, Kihyun92 commented on src/index.js
> +  } = obj;
객체로 받아온걸 구조분해하여 obj에 할당하고 다시 구조분해하는 구조같아요. 이렇게 표현하는건 어떤가요?

```javascript
function render({
  display = 0,
  acc = '',
  operators = [],
  operands = []
}) {

...

```

- https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#%ED%95%A8%EC%88%98_%EB%A7%A4%EA%B0%9C%EB%B3%80%EC%88%98%EB%A1%9C_%EC%A0%84%EB%8B%AC%EB%90%9C_%EA%B0%9D%EC%B2%B4%EC%97%90%EC%84%9C_%ED%95%84%EB%93%9C_%ED%95%B4%EC%B2%B4%ED%95%98%EA%B8%B0

2021-01-21 15:48 UTC, Kihyun92 commented on src/index.js
> +      {[1, 2, 3, 4, 5, 6, 7, 8, 9, 0].map((num) => (<button type="button" onClick={() => render(numberClick(num, acc, operators, operands))}>{num}</button>))}
`[1, 2, 3, 4, 5, 6, 7, 8, 9, 0]` 이 배열은 앞으로 변하지 않을 값 같아요. 함수 바깥으로 분리한다면 재사용성 및 테스트에 용이해질 것 같아요~

2021-01-22 00:13 UTC, 2Zero1 commented on src/index.js
> +      {[1, 2, 3, 4, 5, 6, 7, 8, 9, 0].map((num) => (<button type="button" onClick={() => render(numberClick(num, acc, operators, operands))}>{num}</button>))}
힘수 바깥으로 분리라면 인자값으로 받으란 건가요 ?? 아니면 외부 함수로 부터 받아오란 말씀이신거에요 ??

2021-01-22 00:13 UTC, 2Zero1 commented on src/index.js
> +      {[1, 2, 3, 4, 5, 6, 7, 8, 9, 0].map((num) => (<button type="button" onClick={() => render(numberClick(num, acc, operators, operands))}>{num}</button>))}
> `[1, 2, 3, 4, 5, 6, 7, 8, 9, 0]` 이 배열은 앞으로 변하지 않을 값 같아요. 함수 바깥으로 분리한다면 재사용성 및 테스트에 용이해질 것 같아요~

힘수 바깥으로 분리라면 인자값으로 받으란 건가요 ?? 아니면 외부 함수로 부터 받아오란 말씀이신거에요 ??

2021-01-22 18:04 UTC, Kihyun92 commented on src/index.js
> +      {[1, 2, 3, 4, 5, 6, 7, 8, 9, 0].map((num) => (<button type="button" onClick={() => render(numberClick(num, acc, operators, operands))}>{num}</button>))}
제가 설명이 부족했네요 ㅎㅎ 

``` javascript
const numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 0];
```

위와 같이 변하지 않는 상수값은 render 함수 바깥에 선언해서 사용하는게 좋을 것 같다는 의미였어요

2021-01-23 12:08 UTC, 2Zero1 commented on src/index.js
> +}
객체를 리턴하는 부분을 numberClick과 operatorClick 두 곳에서 중복되어 사용 하고 있어서 함수로 뺐습니다.
중복해서 사용하는게 나을까요 ?

2021-01-23 12:09 UTC, 2Zero1 commented on src/index.js
> +function numberClick(num, acc, operators, operands) {
위의 방법대로 인자를 객체로 받고, 기본값을 넣어주려고 하면 에러가 발생합니다...ㅠㅠ

2021-01-23 12:09 UTC, 2Zero1 commented on src/index.js
> +  } = obj;
{
  display: 0, acc: '', operators: [], operands: [],
}

2021-01-23 12:25 UTC, 2Zero1 commented on src/index.js
> +      {[1, 2, 3, 4, 5, 6, 7, 8, 9, 0].map((num) => (<button type="button" onClick={() => render(numberClick(num, acc, operators, operands))}>{num}</button>))}
이해 되었습니다. 
감사합니다 ^^

2021-01-23 15:09 UTC, Kihyun92 reviewed
이번 과제를 하면서 많은 고민 중이신 것 같아요. 고민하신 부분들을 잘 기억해두시고 아샬님의 과제 풀이 영상을 반복해서 보시면서 본인의 부분으로 가져가시면 좋겠습니다.

특히 아샬님은 어떻게 문제를 풀어나가는지 풀이과정을 눈여겨 보시면 좋을 것 같아요~

2021-01-25 12:19 UTC, merged