1차 커밋
CodeSoom/react-week1-assignment-2 pull request #64
Opened 2021-01-20 12:24 UTC by yoonhe

## 질문

1. 숫자와 연사자를 구분하기 위해 `isNaN`을 사용하였는데 eslint 에러가 뜹니다.. `isNaN`을 사용하면 안되나요?
2.  아래의 테스트를 통과하기위해 어떻게 접근해야할지 감이 안잡힙니다.. 
  ```js
  Scenario('연산자를 입력한 후 다시 숫자를 입력하면 새로 입력한 숫자가 표시됩니다.', (I) => {
    I.amOnPage('/');
  
    ['4', '3', '+', '2', '1'].forEach((it) => I.click(it));
  
    I.dontSee('43');
    I.see('21');
  });
  ```
현재 `1`이라는 버튼을 클릭하고 `2`라는 버튼을 클릭하면 `12`가 화면에 그려지고 그 후에 `*` 버튼을 클릭하고 `3` 버튼을 클릭하면 바로 계산이 되어 버리는데 이때 바로 계산이 되지 않고 숫자인 버튼들을 합쳐서 다시 계산해주려면 어떻게 해야하는지 감이 잡히지 않습니다 ㅜㅜ

2021-01-20 13:41 UTC, yoonhe commented
통과가 되지 않았던 아래의 테스트는 숫자 버튼과 연산자 버튼의 `onClick` 함수를 각각 분리하여 해결했지만

```js
Scenario('연산자를 입력한 후 다시 숫자를 입력하면 새로 입력한 숫자가 표시됩니다.', (I) => {
  I.amOnPage('/');

  ['4', '3', '+', '2', '1'].forEach((it) => I.click(it));

  I.dontSee('43');
  I.see('21');
});
```



현재는 `1` 버튼 클릭 `+` 버튼 클릭 `2` 버튼 클릭  후 또 한번  `+`을 클릭해야 앞전의 `1+2`의 결과값이 반환되게 구현을 해두어서 아래의 테스트 처럼 `43 + 21` 이렇게 뒤에 연산자가 오지 않으면 값을 반환하지 않아서 테스트가 통과하지 않는것 같습니다.. 

내일 좀더 코드를 수정해보도록 할게요..!

```js
Scenario('연산자를 입력한 후 다시 숫자를 입력하면 새로 입력한 숫자가 표시됩니다.', (I) => {
  I.amOnPage('/');

  ['4', '3', '+', '2', '1'].forEach((it) => I.click(it));

  I.dontSee('43');
  I.see('21');
});
```

2021-01-20 15:38 UTC, Kihyun92 commented
> 제가 연산자 버튼을 눌렀을시에 결과값이 반환되게 구현해둬서 `45 + 45 +` 이렇게 와야지만 계산이 가능 한데 ... 아래의 테스트처럼 `45 + 45` 이런 상황이라면 계산하는 시점을 어떻게 잡아줘야 할까요?... 현재는 연산자 버튼을 통해 계산이 되도록 구현해뒀는데... 연산자 버튼이 뒤에 오지 않는 경우에는 어떻게 해야할지 모르겠습니다 ㅜㅜ

이 부분 잘 이해가 되지 않는데요, `45+45`와 같이 과제에서 연산자 버튼이 뒤에 오지 않을때 계산이 되는 경우가 있나요?

2021-01-20 15:48 UTC, Kihyun92 requested changes

2021-01-20 15:48 UTC, Kihyun92 commented on src/index.js
> +/* eslint linebreak-style: ["error", "windows"] */
혹시 에디터 우측 하단에 CRLF -> LF로 변경해보셨나요??

2021-01-20 15:48 UTC, Kihyun92 commented on src/index.js
> +          ))
이 부분에 예외처리와 형변환이 들어가게 된 이유가 무엇일까요?

숫자들과 연산자들을 같은 배열에서 관리해야할 이유가 있을까요?

2021-01-20 15:48 UTC, Kihyun92 commented on src/index.js
> +    }
if 문을 사용하지 않고 해결하는 방법이 있을까요?

2021-01-20 15:48 UTC, Kihyun92 commented on src/index.js
> +function render(originNum = '', operator, addNum = '') {
render에 많은 파라미터들이 넘어오고 있어 복잡해지는것 같습니다. 이 상태값들을 같은 의미를 가지는 객체로 묶는건 어떨까요?

2021-01-20 15:48 UTC, Kihyun92 commented on src/index.js
> +    const formatAddNum = Number(addNum);
형변환이 필요하게 된 원인이 무엇일까요?

2021-01-21 01:01 UTC, yoonhe commented on src/index.js
> +/* eslint linebreak-style: ["error", "windows"] */
오.. 감사합니다 변경하니 에러가 잡히지 않네요 해당 주석은 삭제할게요!

2021-01-21 01:08 UTC, yoonhe commented on src/index.js
> +    }
switch를 사용하면될까요???

2021-01-21 03:06 UTC, yoonhe commented on src/index.js
> +          ))
말씀하신 부분 참고해서 아래와같이 바꾸었습니다. 아직 푸쉬는 하지 않았어요!

```js
<p>
        {
          [1, 2, 3, 4, 5, 6, 7, 8, 9, 0].map((number) => (
            <button type="button" onClick={() => onClickNumberButton(number)}>{number}</button>
          ))
        }
      </p>
      <p>
        {
          ['+', '-', '*', '/', '='].map((operatorText) => (
            <button type="button" onClick={() => onClickOperator(operatorText)}>{operatorText}</button>
          ))
        }
      </p>
```

2021-01-21 03:10 UTC, yoonhe commented on src/index.js
> +function render(originNum = '', operator, addNum = '') {
`render({ originNum, operator, addNum })` 하나의 객체로 합쳐주었습니다

2021-01-21 03:13 UTC, yoonhe commented on src/index.js
> +    const formatAddNum = Number(addNum);
1 버튼을 누른 뒤 2 버튼을 누르면 숫자를 합해주는게아니라 문자열로 합쳐줘야해서  `render({ originNum: `${originNum}${clickText}` })` 이런식으로 합쳐진 문자열을 render 함수에 보내주게 되는데 이때 `+` 라는 연산자로 연산을 해주려면 문자열을 숫자로 바꿔주어야해서 형변환을 해주었습니다.. 형변환없이 연산을 하려면 어떻게 해야하나요?

2021-01-21 03:15 UTC, yoonhe commented
> 이 부분 잘 이해가 되지 않는데요, 45+45와 같이 과제에서 연산자 버튼이 뒤에 오지 않을때 계산이 되는 경우가 있나요?
그리고 첨부해주신 테스트 코드가 아래와 동일한 것 같은데 맞나요?\

```
Scenario('연산자를 입력한 후 다시 숫자를 입력하면 새로 입력한 숫자가 표시됩니다.', (I) => {
  I.amOnPage('/');

  ['4', '3', '+', '2', '1'].forEach((it) => I.click(it));

  I.dontSee('43');
  I.see('21');
});
```

해당 부분은 제가 테스트를 잘못이해하고 있었습니다.. 43 + 21을 하면 64가 화면에 보여야하는줄 알았어요..

2021-01-21 03:24 UTC, yoonhe commented on src/index.js
> +    const formatAddNum = Number(addNum);
혹시 애초에 render함수에서 인자로 넘겨줄때 아래처럼 합쳐진 문자열 앞에 `+`를 넣어서 숫자로 바꿔 넘겨주는방법은 괜찮은 해결방안일까요?
```
render({ originNum: +`${originNum}${clickText}` });
```

2021-01-21 14:08 UTC, yoonhe commented on src/index.js
> +    }
if문을 아래와같이 없애주었는데.. 알맞게 접근한게 맞을까요?ㅎㅎㅎㅎㅎㅎㅎ

```
const operatorFn = operator && {
    '+': originNum + addNum,
    '-': originNum - addNum,
    '*': originNum * addNum,
    '/': originNum / addNum,
  };

  function onClickOperator(operatorText) {
    return addNum ? render({
      originNum: operatorFn[operator], operator: operatorText,
    }) : render(
      { originNum, operator: operatorText },
    );
  }
```

2021-01-21 16:14 UTC, Kihyun92 commented on src/index.js
> +    const formatAddNum = Number(addNum);
애초에 문자열로 처리하지 않으면 어떤가요? 예를들어서 1인데 5를 누르면 15가되죠. 근데 사실 15는 10 + 5 입니다.

2021-01-21 16:23 UTC, Kihyun92 requested changes

2021-01-21 16:23 UTC, Kihyun92 commented on src/index.js
> +  };
이 로직은 변하지 않을 것 같아요. 그리고 재사용과 테스트가 용이하도록 render 함수 바깥에 선언하는건 어떨까요?
그리고 변수 네이밍은 줄여서 쓰지 않는걸 추천합니다. 본인밖에 모를 수 있고, 동료들이 읽을때 이해하기 더 쉬울 것 같아요.

``` javascript
const operatorFunctions = {
    '+': (x, y) => x + y,
    '-': (x, y) => x - y,
    '*': (x, y) => x * y,
    '/': (x, y) => x / y,
  };

//  호출
const result = operatorFunctions[operator](x, y);
```

2021-01-21 16:23 UTC, Kihyun92 commented on src/index.js
> +render({ originNum: '' });
render함수의 매개변수에 `default value` 설정을 해두면 초기에 값을 넘기지 않아도 될 것 같아요~

```javascript
function render({ originNum = '', operator, addNum }) {
```

2021-01-21 16:23 UTC, Kihyun92 commented on src/index.js
> +  }
예외처리가 추가되고 복잡해지는 원인이 무엇일까요? 그리기와 계산하는 로직을 분리해보면 좋을 것 같아요!

2021-01-21 23:33 UTC, yoonhe commented on src/index.js
> +    const formatAddNum = Number(addNum);
기현님 아래의 테스트 처럼 눌렀을때는 `40 + 3`이 되게 구현해줘야 하는거죠?

```js
 I.amOnPage('/');

  I.click('4');
  I.click('3');

  I.see('43');
```

2021-01-22 10:56 UTC, yoonhe commented on src/index.js
> +render({ originNum: '' });
반영했습니다!

```js
const initialState = { originNum: '', operator: null, addNum: null };

function render({ originNum, operator, addNum } = initialState) {}
```

2021-01-22 13:06 UTC, yoonhe commented on src/index.js
> +render({ originNum: '' });
위의 코드가 최초의 렌더링시에만 적용이되어서 아래와같이 다시 설정해주었습니다 
```js
function render({ originNum = [], operator = null, addNum = [] } = {}) {}
```

2021-01-22 13:08 UTC, yoonhe commented on src/index.js
> +  }
아래와같이 변경하였습니다

function onClickNumberButton(clickText) {
    // 계산하는 로직
    const renderState = operator
      ? { originNum, operator, addNum: [...addNum, clickText] }
      : { originNum: [...originNum, clickText] };

    return render(renderState); // 그리는 로직
  }

2021-01-22 13:13 UTC, yoonhe commented on src/index.js
> +    const formatAddNum = Number(addNum);
```
   [1,2,3] / lastNumberIndex => 2
   
   100 + 20 + 3
   1 * 100 => Math.pow(10, 2)
   2 * 10 => Math.pow(10, 1)
   3 * 1
```
버튼 클릭을 통해 들어온 숫자 배열을 `numberMaker`라는 함수를 통해 숫자로 변환해주었습니다.

```js
function numberMaker(numbers) {
  if (!Array.isArray(numbers)) return numbers;

  const lastNumberIndex = numbers.length - 1;

  return numbers.reduce((accumulrator, currentValue, index) => {
    const exponent = lastNumberIndex - index;
    const convertCurrentValue = index === lastNumberIndex
      ? currentValue : currentValue * 10 ** exponent;

    return accumulrator + convertCurrentValue;
  }, 0);
}

function onClickNumberButton(clickText) {
    const renderState = operator
      ? { originNum, operator, addNum: [...addNum, clickText] }
      : { originNum: [...originNum, clickText] };

    return render(renderState);
  }
```

2021-01-22 18:38 UTC, Kihyun92 requested changes

2021-01-22 18:38 UTC, Kihyun92 commented on src/index.js
> +  '/': (originNum, addNum) => originNum / addNum,
origin, add와 같은 정보는 필요 없을 것 같습니다.

단순하게 x, y와 같이 표현하는건 어떨까요?

2021-01-22 18:38 UTC, Kihyun92 commented on src/index.js
> +}
오우,, 굉장히 복잡하네요. 단순히 `이전값 * 10 + 최신값` 과 같이 처리할 순 없을까요? 어떤 부분이 복잡하게 만들고 있는 걸까요?

2021-01-22 18:38 UTC, Kihyun92 commented on src/index.js
> +        {addNum.length !== 0 ? numberMaker(addNum) : numberMaker(originNum)}
부정문으로 예외처리하는것은 좋지 않습니다. 읽는 사람에게 두번 고민하게 만들죠.

2021-01-22 18:38 UTC, Kihyun92 commented on src/index.js
> +    return operator && addNum.length !== 0
부정문으로 예외처리를 하는것은 좋지 않습니다. 가독성 측면에서도 그렇죠.

그리고 operator와 addNum에 대해서 예외처리가 많네요. 이 부분은 계산할때 처리해줄 순 없을까요? 🤔

이 값들이 있다면, 연산을하고, 없다면 기존 값을 사용하는 방법으로요.

2021-01-23 05:44 UTC, yoonhe commented on src/index.js
> +    return operator && addNum.length !== 0
```js
return render({
      originNum: operatorFunctions[operator] ? operatorFunctions[operator](
        numberMaker(originNum),
        numberMaker(addNum),
      ) : originNum,
      operator: operatorText,
    });
```
`operatorFunctions[operator]` 가 있다면 연산을 해주고 없을땐 `originNum`을 반환하도록 수정하였습니다. 제가 말씀하신 부분을 제대로 이해한게 맞을까요 ?..!

2021-01-23 05:54 UTC, yoonhe commented on src/index.js
> +}
우아 말씀해주신대로 해보니 코드가 줄었어요..! 감사합니다 

```js
numbers.reduce((acc, cur) => (acc * 10) + cur, 0);
```

2021-01-23 06:00 UTC, yoonhe commented on src/index.js
> +        {addNum.length !== 0 ? numberMaker(addNum) : numberMaker(originNum)}
>  operator와 addNum에 대해서 예외처리가 많네요. 이 부분은 계산할때 처리해줄 순 없을까요?
 🤔 이 값들이 있다면, 연산을하고, 없다면 기존 값을 사용하는 방법으로요.
 
 위의 리뷰 참고해서 아래와같이 변경해보았습니다

addNum이 빈배열이라면 `numberMaker`에서 `0`을 반환해 뒤에 있는 값을 계산하고, 빈배열이 아니라면  `numberMaker(addNum)`를 사용하도록 구현해주었습니다
 
```js
numberMaker(addNum) || numberMaker(originNum)
```

2021-01-23 15:04 UTC, Kihyun92 approved these changes
고생하셨습니다 ㅎㅎ 리뷰를 잘 반영해주신 것 같아요 🙏 처음 작성한 코드와 마지막 코드를 비교하면서 어떤 변화가 일어났는지 보시면 좋을 것 같습니다.

그리고 과제풀이 영상을 통해서 반복해서 복습해보시면 좋겠습니다. 특히 아샬님은 어떻게 문제를 풀어나가는지 풀이과정을 눈여겨 보시면 좋을 것 같아요 ☺️

2021-01-25 12:24 UTC, merged