Feature/simple calculator
CodeSoom/react-week1-assignment-2 pull request #65
Opened 2021-01-20 12:41 UTC by bluel00

let을 제거하면서 전체적으로 뜯어고쳤습니다. 

시행착오
1. 클래스를 생성해서 게터 세터로 상태값과 내부 메서드 관리
  - 기껏 let을 없애고 있는데 Immutable 한게 맞나? 라는 생각이 들어서 폐기.

render함수의 파라미터가 너무 많아졌는데 어떻게 할지 고민중입니다.

onClick의 화살표 함수 안에서 비구조화 객체로 바로 넘기고 받으려 했더니 빨간줄이 안없어져서 공부중입니다; ㅠ

2021-01-20 15:56 UTC, Kihyun92 requested changes
> render함수의 파라미터가 너무 많아졌는데 어떻게 할지 고민중입니다.

좋은 고민을 해보고 계신 것 같아요! 👍🏼 
고민하신대로 파라미터들로 인해 코드가 많이 복잡해진 상태같아요.

이런 경우 파라미터를 객체로 만들면 해결이 됩니다.
``` javascript
render({
  currentNumber: result,
  currentNumber: 0, 
  previousNumber: 0, 
  storedOperator: '',
});
```
1. named parameter처럼 파라미터에 이름을 붙이는 것처럼 표현력이 좋아집니다.
2. optional한 값을 다루기가 쉬워집니다.
3. 의미있는 파라미터들을 객체로 묶을 수 있습니다.

See also

- https://github.com/hannut91/refactoring-practice/tree/master/6.8-introduce-parameter-object
- https://refactoring.com/catalog/introduceParameterObject.html

2021-01-20 15:56 UTC, Kihyun92 commented on src/index.js
> +const render = (left = 0, operator, right, result, currentState = 'left') => {
render에 많은 파라미터들이 넘어오고 있어 복잡해지는 것 같아요. 이 상태값들을 같은 의미를 가지는 객체로 묶는건 어떨까요?

2021-01-20 15:56 UTC, Kihyun92 commented on src/index.js
> +};
if 를 사용하지 않고 처리하는 방법은 없을까요? 🤔

2021-01-20 15:56 UTC, Kihyun92 commented on src/index.js
> +};
display의 역할이 무엇인가요? 이 함수가 필요하게된 원인이 무엇 일까요?

2021-01-21 12:58 UTC, bluel00 commented
calculate 함수의 if문을 제거했습니다.

2021-01-21 12:59 UTC, bluel00 commented on src/index.js
> +};
조건들을 객체에 키로 넣고 value에 함수를 넣어 수정했습니다.

2021-01-21 13:06 UTC, bluel00 commented on src/index.js
> +};
좌변과 우변이 있는 식을 유지하고 커서가 움직이면 되겠다싶어 그 컨셉만 가지고 별다른 준비없이 구현을 시작했는데
뒤로갈수록 너무 몸이 힘든 길을 택한거 같습니다.
현재상태에 따라 좌변, 우변, 결과값 3개중 하나를 보여주려다보니 이렇게 됐습니다.ㅠ

2021-01-21 13:18 UTC, bluel00 commented on src/index.js
> +const render = (left = 0, operator, right, result, currentState = 'left') => {
네 다음 커밋에 반영하겠습니다.

2021-01-21 16:27 UTC, Kihyun92 commented on src/index.js
> +};
틀린 방법은 아닙니다. 하지만 상태가 너무 많은 것 같아요. 현재 상태 및 좌변, 우변, 결과 값을 알고 있어야하고 현재 상태에 따라 예외처리들이 복잡해지겠네요. 

일단 그려주는 부분과 계산하는 부분을 분리하는 것 부터 시작하면 좋을 것 같습니다. 그리고 좌변이 결과값이 될 순 없을까요? 누적되는 값과 새로 입력되는 값, 그리고 연산자만 관리해도 예외처리가 조금 더 줄어들 것 같네요~

2021-01-21 16:33 UTC, Kihyun92 requested changes

2021-01-21 16:33 UTC, Kihyun92 commented on src/index.js
> +    '/': divide(Number(left), Number(right)),
형변환없이 이 문제를 해결할 수 있을까요?

2021-01-21 16:33 UTC, Kihyun92 commented on src/index.js
> +  };
이 함수에서 render까지 관여하고 있는 게 복잡함의 원인일 겁니다.

그리기와 계산을 분리해보세요:)

2021-01-22 12:53 UTC, bluel00 commented on src/index.js
> +};
일단 그려주는 부분과 계산하는 부분을 분리하기위해 

render를 밖으로 빼고 객체를 리턴하도록 수정했습니다.

2021-01-22 12:57 UTC, bluel00 commented on src/index.js
> +    '/': divide(Number(left), Number(right)),
어째선지 쉽지 않네요.
플러스가 말을 안듣습니다;;

2021-01-22 13:02 UTC, bluel00 commented
그리는 부분과 계산하는 부분을 분리해봤습니다.
객체로 넘기고 받는거까지는 수정했습니다.




- [ ]  상태 줄이기
- [ ]  형변환 제거

2021-01-22 13:04 UTC, bluel00 commented
그리는 부분과 계산하는 부분을 분리해봤습니다.
객체로 넘기고 받는거까지는 수정했습니다.

 
- [ ] 상태 줄이기
- [ ] 형변환 제거

2021-01-22 18:48 UTC, Kihyun92 requested changes
코드에 예외처리가 많아요. 함수 내에서 관리하는 상태가 많아 진 것 같아요. 각 함수가 어떤 역할을 하고, 그 역할을 위해서 필요한 상태값은 무엇인지 고민해보시면 좋을 것 같습니다

2021-01-22 18:48 UTC, Kihyun92 commented on src/index.js
> +    return operators[operator];
이렇게도 처리할 수 있겠네요~ 혹은 operators를 calculate함수에서 추출해도 좋을 것 같아요~
```suggestion
  return (x, y) => {
    const operators = {
      '+': plus(),
      '-': minus(),
      '*': multiply(),
      '/': divide(),
    };
    return operators[operator](x, y);
```

2021-01-22 18:48 UTC, Kihyun92 commented on src/index.js
> +  currentState = 'left',
현재 상태가 필요한 이유가 결국 좌변과 우변을 관리하기 위해서인거죠?

매개변수가 많아질수록 코드 복잡도는 굉장히 높아집니다. 그리고 해당 함수가 의도보다 더 많은 역할을 하고 있다는걸 나타내주기도 하죠.

2021-01-24 03:51 UTC, bluel00 commented
과제풀이 영상을 보고 부족한 부분들을 수정했습니다.

1. 매개변수가 많아 코드가 복잡하다.
- 상태의 수를 accumulator , number, operator 3개로 줄였더니 복잡한 if문이 필요 없어졌습니다.

2. 형변환 없이 코드 작성.
- 어떤 상황에서는 문자열로 받아 concat으로 붙이고, 다른상황에서는 Number로 받아 계산을 하려하다보니 형변환이 필요했습니다.
- 항상 계산만 하게함으로써 해결할 수 있었습니다.
- **일관성 있는 API를 사용하자.**

2021-01-24 08:14 UTC, bluel00 commented
https://www.notion.so/1-e3a236d186474e82911eed183a1153d0

1주차 회고입니다.

2021-01-24 14:23 UTC, Kihyun92 approved these changes
고생하셨습니다~ 과제 풀이 영상을 보실땐 아샬님은 문제를 어떻게 풀어나가는지 그 과정을 눈여겨 보시면 도움 될 것 같아요 :)
회고도 확인했습니다 👍  덕분에 저도 자극받게 되네요 ㅎㅎ

2021-01-24 14:26 UTC, merged