Implement simple calculator
CodeSoom/react-week1-assignment-2 pull request #66
Opened 2021-01-20 16:05 UTC by ErickRyu

2021-01-21 16:47 UTC, Kihyun92 requested changes

2021-01-21 16:47 UTC, Kihyun92 commented on src/utils/stack.js
> +module.exports = { Stack };
stack을 구현해서 해결해보셨네요! 좋습니다. 다만, push명령어는 store의 값을 직접 고칩니다. 변수가 중간에 바뀌는거죠. 그러면 코드가 어떻게 동작할지 예측하기가 굉장히 어려워집니다. 이는 과제 1에서 배운 것을 상기해보시면 좋을 것 같아요.

render함수가 외부 변수에 의해 동작이 변화하지 않게 해결할 수는 없을까요?

2021-01-21 16:47 UTC, Kihyun92 commented on src/index.js
> +    }
switch를 사용하지 않고 해결할 수 있을까요?🤔

2021-01-21 16:47 UTC, Kihyun92 commented on src/index.js
> +  addDigitRight(number) {
right이 무엇일까요? 동료가 보기에 어떤 역할을 하는 함수인지 알 수 있는 네이밍이면 좋을 것 같아요~

2021-01-21 16:49 UTC, Kihyun92 commented
풀 리퀘스트를 CodeSoom:<user-github-id>로 보내주세요~

추가로 풀 리퀘스트에 어떤 작업인지 간단하게라도 내용을 적어주시면 좋을 것 같습니다 ☺️

2021-01-23 14:29 UTC, Kihyun92 commented
@ErickRyu 님, 어떻게 진행되고 있나요~? 커맨트 확인 부탁드립니다.

추가로 과제풀이 영상을 가능하면 반복해서 보시고, 본인의 것으로 만들어 보시면 좋을 것 같아요. 특히 아샬님은 어떻게 문제를 풀어나가는지 풀이과정을 눈여겨 보시면 좋을 것 같습니다.

2021-01-24 05:48 UTC, ErickRyu commented on src/index.js
> +    }
이 부분은 다형화를 이용해봤는데, 다른 방법도 있을까요?

2021-01-24 05:48 UTC, ErickRyu commented on src/index.js
> +  addDigitRight(number) {
저는 addDigitToRight 말고는 적당한 답이 떠오르지 않는데요. 혹시 어떤 네이밍이 더 이해가 잘 가실까요?

2021-01-24 05:49 UTC, ErickRyu commented on src/utils/stack.js
> +module.exports = { Stack };
이번 커밋에서 이건 아직 해결을 안 해놨습니다. 과제1을 참고해서 다시 작성을 해볼게요!

2021-01-24 15:07 UTC, Kihyun92 commented on src/index.js
> +    }
아래 처럼 lookup을 함수로 만들고, 해당 lookup을 바로 호출하는 형식은 어떤가요?

``` javascript
// calculate 함수 lookup
const operators = {
    '+': (x, y) => x + y,
    '-': (x, y) => x - y,
    '*': (x, y) => x * y,
    '/': (x, y) => x / y,
  };

//  호출
const result = calculate[operator](x, y);
```

참고
- https://omwri.medium.com/javascript-patterns-lookup-tables-26bbaf693e24

2021-01-24 15:10 UTC, Kihyun92 commented on src/index.js
> +  addDigitRight(number) {
음 굳이 right라는 용어는 제거하고, 해당 함수가 기존 입력값에 10을 곱하고 추가로 들어오는 값을 더해주어 10진수 값을 만들어 주는 역할을 하고 있는 것 같아요. makeDigits라고 해볼 수도 있을 것 같아요. 더 나은 네이밍이 있을 것 같기도 하네요 🤔

2021-01-26 12:13 UTC, merged