계산기 구성하기
CodeSoom/react-week1-assignment-2 pull request #71
Opened 2021-01-22 11:12 UTC by Najeong-Kim

코드를 수정해보았으나 확실한 아이디어가 떠오르지 않아
먼저 계산기 형태만 구성해보았습니다!

2021-01-22 18:02 UTC, Kihyun92 reviewed
막막하거나 맞는 방향으로 잘 하고 있는지 모르실땐, 가능한 작은 기능 단위로 쪼개고 하나하나 해결 해보는건 어떨까요?

예를 들면 숫자 버튼 눌렀을때 숫자 노출되게하고, 그 다음 십의 자리, 백의 자리수까지 표현이 가능하게 하고, 다음으로 더하기 기능도 추가하는 방식 처럼요. 이런식으로 점진적으로 작업을 진행해보셔도 좋을 것 같습니다~

그리고 중간 중간 의미있는 성과가 나타났을때 커밋을 남김으로써 혹시라도 길을 잃었을 경우, 다시 돌아갈 수 있게 하는 것도 좋을 것 같습니다 :)

2021-01-23 12:30 UTC, Najeong-Kim commented
네 ㅠㅠ 새로운 값을 넣을 때 기존의 값을 유지하는 법을 생각해보고있어요

2021-01-23 14:22 UTC, Kihyun92 commented
많은 고민 중이신 것 같아요. 어렵겠지만, 직접 한번 구현해보시면 좋겠습니다. 👍

작업 하시고 아샬님의 과제 풀이 영상 꼭 보시면 좋을 것 같아요. 특히 아샬님은 어떻게 문제를 풀어나가는지 풀이과정을 눈여겨 보시면 좋을 것 같습니다.

2021-01-24 13:12 UTC, Najeong-Kim commented
숫자를 넣는것까진 성공했습니다! 사칙연산을 넣는 것이 어렵네요ㅠ

2021-01-24 14:35 UTC, Najeong-Kim commented
생각할 수 있는 최대한으로 코드를 작성했습니다
실행은 되지 않습니다..

2021-01-24 14:42 UTC, Kihyun92 requested changes
끝까지 진행해보고 계신게 좋습니다 👍🏼 

예외처리가 많아질 경우에는 해당 예외처리가 생기는 원인이 뭔지, 해결할 수 없을지 고민해보는것도 좋을 것 같아요.

2021-01-24 14:42 UTC, Kihyun92 commented on src/index.js
> +}
if 를 사용하지 않고 해결하려면 어떻게 할 수 있을까요?

아래 처럼 lookup을 함수로 만들고, 해당 lookup을 바로 호출하는 형식은 어떤가요?

``` javascript
// calculate 함수 lookup
const operators = {
    '+': (x, y) => x + y,
    '-': (x, y) => x - y,
    '*': (x, y) => x * y,
    '/': (x, y) => x / y,
  };

//  호출
const result = calculate[operator](x, y);
```

참고
- https://omwri.medium.com/javascript-patterns-lookup-tables-26bbaf693e24

2021-01-24 14:42 UTC, Kihyun92 commented on src/index.js
> +    }
else 는 사용하지 않고 작성해주세요~

guard clauses 패턴 참고해보세요ㅎㅎ
- https://refactoring.com/catalog/replaceNestedConditionalWithGuardClauses.html

2021-01-27 15:02 UTC, merged