Feature/calculator
CodeSoom/react-week1-assignment-2 pull request #77
Opened 2021-01-24 09:34 UTC by heejinlee07

간단계산기 구현과제

- result : 화면 상에 구현되는 숫자
- operator: 연산자
- buffer1: 연산자 왼쪽에 위치하는 값
- buffer2: 연산자 오른쪽에 위치하는 값

---

1. addNumber()
숫자를 전달받아 연산자의 유무에 따라 buffer1에 저장하거나 buffer2에 저장하는 역할.

2. calculateNumber()
숫자가 연속해서 눌렸을 때 그 숫자를 더해져서 출력하는 역할. 기존값과 비교해서 기존값이 0이면 아무것도 입력되지 않은 상태이므로, 현재값을 그대로 출력하고, 0이 아니라면 이미 입력된 값이 있는 것이므로, 다음 자릿수에 현재값을 출력

3. addOperator()
연산자가 있을 때 호출되는데, 연산자의 종류에 따라 분기하여 처리. 전달된 연산자에 따라서 calculateByOperator()를 호출.  '='일 때는 최종계산된 결과값을 result에 전달하여 화면상에 표시. 단, 연산이 종료되었으므로 연산자는 null로 전달. 이후 또다른 연산자가 입력되면 또 연산을 처리해야하므로 buffer1에 최종계산된 결과값을 저장한다. '='이 아니라 다른 연산자이면서 buffer1, buffer2 값이 있을 경우에도 '='일 때와 로직은 동일하지만, 연산자는 null이 아닌 새로 입력된 연산자를 전달한다. 이 모든 경우가 아닌 때는 전달받은 값을 그대로 render()에 전달한다.

4. calculateByOperator()
전달받은 값과, 연산자를 바탕으로 사칙연산하여 결과값을 출력.

---

이번 과제가 너무 어려웠습니다...😂

2021-01-24 15:04 UTC, Kihyun92 requested changes
맞아요. 쉽지 않은 과제입니다ㅎㅎ 그래도 끝까지 직접 고민해보는 점이 좋네요 👍🏼 

아샬님의 과제 풀이 영상을 보시고, 특히 아샬님은 어떻게 문제를 풀어나가는지 눈여겨 보시면 도움되실 것 같습니다~

2021-01-24 15:04 UTC, Kihyun92 commented on src/index.js
> +};
pre, curr과 같이 변수명을 줄여서 쓰는 것보다 동료들이 네이밍만 보고도 해당 변수들의 역할을 이해할 수 있게 써주는건 어떨까요?

그리고 pre가 0 일때의 예외처리가 왜 필요한걸까요? 어차피 `0 * 10 + 1` 은 1이죠

2021-01-24 15:04 UTC, Kihyun92 commented on src/index.js
> +    }
else, else if는 사용하지 말고 해결해보는건 어떨까요? 코드의 복잡도가 올라가게됩니다.

guard clauses 패턴 참고해보세요ㅎㅎ
- https://refactoring.com/catalog/replaceNestedConditionalWithGuardClauses.html

2021-01-25 16:31 UTC, heejinlee07 commented
@Kihyun92 모두 수정하였습니다!

2021-01-30 14:08 UTC, merged