과제 1-2 계산기 : 레이아웃 완료 (연산 로직 진행중)
CodeSoom/react-week1-assignment-2 pull request #86
Opened 2021-05-08 15:19 UTC by studioLuda

과제 1-2: 계산기 레이아웃만 완료 하였습니다. 

연산 로직 구현후 다시 커밋하겠습니다.
감사합니다!

2021-05-09 08:27 UTC, studioLuda commented
과제 1-2 계산기 제출합니다.
저녁식사후  풀이 강의 듣고 리팩토링 하겠습니다.  
감사합니다.

2021-05-09 14:18 UTC, Kihyun92 requested changes
전반적으로 예외처리가 많아 복잡해보이는 것 같아요. 숫자 입력에 대한 핸들링 함수와 연산자에 대한 핸들링 함수를 분리해보는 건 어떨까요?

과제 풀이 영상을 꼭 확인해보시고, 특히 아샬님은 어떻게 문제를 풀어나가는지 풀이과정을 눈여겨 보시면 좋을 것 같습니다.

슬랙의 주간회고 채널에 회고 꼭 남겨주세요~

2021-05-09 14:18 UTC, Kihyun92 commented on src/index.js
> +    let result = 0;
이번 과제에서도 가능하면 let을 사용하지 않고 해결해보세요~

2021-05-09 14:18 UTC, Kihyun92 commented on src/index.js
> +    }
switch문은 break, default 등으로 인해 실수를 유발하고 가독성을 떨어트리기 때문에 `Object literal lookup` 방식으로 변경해보는 것도 추천드립니다~

참고: 
- https://ultimatecourses.com/blog/deprecating-the-switch-statement-for-object-literals

2021-05-09 14:22 UTC, Kihyun92 requested changes

2021-05-09 14:22 UTC, Kihyun92 commented on src/index.js
> +      </div>
`key`라는 키워드는 html 태그들의 attibute중 하나이기 때문에 가능하면 다른 네이밍을 사용하는게 좋을 것 같아요~

```suggestion
        {numbers.map((number) => (
          <button type="button" id={`num- ${number}`} onClick={() => { handleClick(number) }}>{number}</button>
        ))}
      </div>
      <div>
        {operators.map((operator) => (
          <button type="button" id={`operation-${operator}`} onClick={() => { handleClick(operator) }}>{operator}</button>
        ))}
      </div>
```

참고: 
- https://ko.reactjs.org/docs/lists-and-keys.html

2021-05-09 16:26 UTC, studioLuda commented on src/index.js
> +    let result = 0;
넵!

2021-05-09 16:27 UTC, studioLuda commented on src/index.js
> +    }
네! 알려주셔서 감사합니다 ! 공부하고 적용하겠습니다. (PR닫힌 후에라도)

2021-05-09 16:29 UTC, studioLuda commented on src/index.js
> +      </div>
네 수정하겠습니다!

2021-05-09 16:35 UTC, studioLuda commented
안녕하세요 !

현재 진행 상황 공유드려요.

- 1주차 회고작성 완료
- 과제 1-1 lint 오류 수정 및 push 완료
- 과제 1-2 해설 영상 보고 과정 그대로 따라하기 완료
- 제출한 과제 1-2 리팩토링은 아직 진행하지 못했습니다. (미완료) 

1주차 피드백 코멘트는 일요일로 끝난걸로 알고있어요.
알려주신 내용들은 월요일에 틈틈히 정리하고 반영할께요 (스스로 진행하고, 개인 레포에 업로드하던지 하려고요  ^^) 

피드백 감사드려요! 좋은밤 되세요!

2021-05-10 13:59 UTC, Kihyun92 commented
진행하시다가 의논이 필요한 부분이 있다면 DM 주시거나 슬랙의 리액트-4기 채널에 올려주세요~ 다른 동료에게 도움이 될 수 있습니다.

2021-08-08 07:46 UTC, merged